'use strict';
// Injected transport/storage only: no operating HTTP, browser session, DB or provider.
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const crypto=require('node:crypto').webcrypto;
const ui=require('../mockups/shared/admin-commerce-support.js');
const ID='00000000-0000-4000-8000-000000000001',EV='00000000-0000-4000-8000-000000000002',OTHER='00000000-0000-4000-8000-000000000003',HASH='a'.repeat(64),TAG='b'.repeat(64);
const no='ORD-EXAMPLE-01',meta={orderNo:no,connection:'ready',detailState:'ready',generation:1,selection:1,renderSerial:1};
const actor=role=>({authenticated:true,operator:{operator_id:7,role:role||'operator',status:'활성',name:'PRIVATE-NAME',email:'PRIVATE-EMAIL'}});
const caseValue=(patch={})=>({case_id:ID,origin:'customer',state:'open',revision:1,recorded_at:1791200000,updated_at:1791200000,...patch});
const event=(patch={})=>({event_id:EV,case_id:ID,action:'create_inquiry',author_kind:'customer',actor:{kind:'customer',user_id:5,owner_scope:HASH},body:'격리 검증용 문의',visible:true,reply_event_id:null,revision:1,recorded_at:1791200000,...patch});
const common={version:'commerce_support_v1',state:'confirmed',order_no:no,checked_at:1791200000};
const cases=(items=[caseValue()],next_cursor=null)=>({...common,cases:items,next_cursor});
const events=(items=[event()],c=caseValue(),next_cursor=null)=>({...common,current_case:c,events:items,next_cursor});
function receipt(cmd,patch={},currentPatch={}){const r={...caseValue({origin:cmd.action==='record_external_contact'?'external_record':'customer',revision:cmd.expected_revision+1,state:cmd.action==='close'?'closed':'open'}),event_id:EV,action:cmd.action,event_body:cmd.body||'저장 초안 본문',visible:cmd.action==='publish_customer_reply'||['close','reopen'].includes(cmd.action),delivery:'not_attempted',...patch};return {...common,current_case:{...caseValue(r),...currentPatch},operation_result:{operation_id:cmd.operation_id,request_hash:HASH,commit_id:OTHER,result:r}};}
const response=(value,status=200,type='application/json')=>({ok:status>=200&&status<300,status,headers:{get:()=>type},json:async()=>value});
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
function storage(){const data=new Map();return {data,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
function harness(options={}){const calls=[],states=[],ss=options.storage||storage();let role='operator',deny=0;
  const fetch=async(url,init)=>{calls.push({url,init:{...init,signal:undefined}});if(options.fetch)return options.fetch(url,init);if(url==='/api/admin/auth/me')return response(actor(role));if(init.method==='POST')return options.post?options.post(JSON.parse(init.body),init):response(receipt(JSON.parse(init.body)));return response(url.includes('case_id=')?events():cases());};
  const controller=ui.createController({fetch,crypto,storage:ss,onState:s=>states.push(s),onDeny:()=>deny++});
  return {controller,calls,states,ss,setRole:r=>role=r,denials:()=>deny,posts:()=>calls.filter(c=>c.init.method==='POST')};}
const marker=(patch={})=>({version:'support_attempt_v1',uncertain:true,operation_id:ID,action:'internal_note',case_id:ID,expected_revision:1,reply_event_id:null,request_hash:null,scope_tag:TAG,...patch});
function domHarness(){const listeners={},doc={activeElement:null};let subscriber;
  const slot={innerHTML:'',contains:n=>n?.inSlot===true,querySelector(selector){let tag;if(selector.startsWith('#'))tag=[...this.innerHTML.matchAll(/<(?:h3|textarea|select)\b[^>]*>/g)].map(x=>x[0]).find(x=>x.includes('id="'+selector.slice(1)+'"'));else{const match=selector.match(/^\[data-acs(-action)?="([a-z_]+)"\]$/);if(match)tag=[...this.innerHTML.matchAll(/<button\b[^>]*>/g)].map(x=>x[0]).find(x=>x.includes('data-acs'+(match[1]||'')+'="'+match[2]+'"'));}if(!tag)return null;const data={};for(const m of tag.matchAll(/data-acs(-action)?="([a-z_]+)"/g))data[m[1]?'acsAction':'acs']=m[2];return {id:(tag.match(/id="([^"]+)"/)||[])[1]||'',disabled:tag.includes(' disabled'),dataset:data,inSlot:true,focus(){doc.activeElement=this;},closest(){return this;}};}};
  const root={ownerDocument:doc,querySelector:s=>s==='#aco-support'?slot:null,addEventListener:(type,fn)=>(listeners[type]||=[]).push(fn),commerceOrders:{subscribeDetail(fn){subscriber=fn;fn({...meta,detailState:'idle'});return ()=>subscriber=null;},deny(){root.denied=true;subscriber?.({...meta,connection:'denied',orderNo:null});}},commerceOrdersTransport:{dispose(){root.transportDisposed=true;}}};
  const dispatch=(type,target)=>listeners[type]?.forEach(fn=>fn({target}));return {root,slot,doc,dispatch,notify:meta=>subscriber?.(meta)};
}
async function until(predicate){for(let i=0;i<200&&!predicate();i++)await new Promise(r=>setTimeout(r,2));assert(predicate(),'expected asynchronous request boundary');}
async function run(){let checks=0;async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
await check('native current principal is required; PII and role claims are not copied',()=>{assert.deepEqual(ui.principal(actor()),{operator_id:7,role:'operator'});for(const v of [null,{authenticated:true},{...actor(),authenticated:false},actor('admin'),{...actor(),operator:{...actor().operator,status:'중지'}}])assert.throws(()=>ui.principal(v));});
await check('body uses scalar and UTF8 bounds, preserves meaningful text, rejects injection/control/lone surrogate',()=>{const c=caseValue();assert.equal(ui.command('internal_note',c,'  원문\n본문 😀  ',ID).body,'원문\n본문 😀');for(const text of ['', ' ', '<img>', '\u0000', '\ud800', '가'.repeat(4001),'😀'.repeat(3001)])assert.throws(()=>ui.command('internal_note',c,text,ID));});
await check('external/internal/draft/publish/closed transitions retain separate native commands',()=>{assert.equal(ui.command('record_external_contact',null,'외부 문의',ID).case_id,null);assert.equal(ui.command('internal_note',caseValue({state:'closed'}),'메모',ID).expected_revision,1);for(const a of ['record_reply','close'])assert.throws(()=>ui.command(a,caseValue({state:'closed'}),'본문',ID));assert.throws(()=>ui.command('reopen',caseValue(),'사유',ID));const draft=event({action:'record_reply',author_kind:'operator',actor:{kind:'operator',operator_id:7},visible:false});const cmd=ui.command('publish_customer_reply',caseValue(),'바뀐 입력',ID,draft);assert.equal(cmd.reply_event_id,EV);assert(!Object.hasOwn(cmd,'body'));assert.throws(()=>ui.command('publish_customer_reply',caseValue({origin:'external_record'}),'',ID,draft));assert.throws(()=>ui.command('publish_customer_reply',caseValue(),' ',ID,event()));});
await check('bad envelopes, wrong targets and private/public contradictions fail closed',()=>{for(const value of [{...cases(),version:'v2'},{...cases(),order_no:'other'},{...cases(),cases:[caseValue(),caseValue()]},{...cases(),next_cursor:'?bad'}])assert.throws(()=>ui.envelope(value,no,'cases'));assert.throws(()=>ui.envelope(events(),no,'events',OTHER));assert.throws(()=>ui.envelope(events([event({action:'internal_note'})]),no,'events',ID));assert.throws(()=>ui.envelope(events([event({body:'<script>'})]),no,'events',ID));assert(!JSON.stringify(ui.envelope(events(),no,'events',ID)).includes('owner_scope'));});
await check('invalid native author/action, close state and publication visibility do not become confirmed proof',()=>{assert.throws(()=>ui.envelope(events([event({action:'publish_customer_reply',reply_event_id:OTHER})]),no,'events',ID));assert.throws(()=>ui.envelope(events([event({author_kind:'operator',actor:{kind:'operator',operator_id:7}})]),no,'events',ID));const cmd=ui.command('close',caseValue(),'사유',ID);for(const patch of [{state:'open'},{visible:false}])assert.throws(()=>ui.envelope(receipt(cmd,patch),no,'operation',null,{...cmd,request_hash:null}));});
await check('operation result is immutable original evidence, separate from newer current case',()=>{const cmd=ui.command('close',caseValue(),'종결 사유',ID);const value=receipt(cmd,{}, {state:'open',revision:3});const out=ui.envelope(value,no,'operation',null,{...cmd,request_hash:null});assert.equal(out.operation_result.result.state,'closed');assert.equal(out.current_case.state,'open');assert.equal(out.current_case.revision,3);for(const patch of [{event_body:'바뀐 본문'},{delivery:'sent'},{revision:4}])assert.throws(()=>ui.envelope(receipt(cmd,patch),no,'operation',null,{...cmd,request_hash:null}));});
await check('marker allowlist cannot carry body, PII, role grants or a replacement operation',()=>{for(const patch of [{body:'PRIVATE'},{role:'owner'},{request_hash:'wrong'},{scope_tag:'other'},{case_id:null}])assert.throws(()=>ui.markerView({...marker(),...patch},TAG));const ss=storage(),store=ui.markerStore(ss,TAG,()=>true),m=marker();store.put(m,null);assert.throws(()=>store.put({...m,operation_id:OTHER},m));assert.throws(()=>store.put({...m,action:'record_reply'},m));assert.throws(()=>store.put({...m,expected_revision:2},m));const known=store.put({...m,request_hash:HASH},m);assert.throws(()=>store.put({...known,request_hash:'c'.repeat(64)},known));assert.equal(store.clear(m),false);assert.equal(store.clear(known),true);});
await check('storage write-readback and epoch guard block before POST; stale clear cannot delete',async()=>{for(const kind of ['throw','readback','stale']){const ss=storage();let live=true;const s=ui.markerStore(ss,TAG,()=>live);ss.setItem=(key,value)=>{if(kind==='throw')throw Error('blocked');ss.data.set(key,kind==='readback'?'null':value);if(kind==='stale')live=false;};assert.throws(()=>s.put(marker(),null));assert.equal(s.clear(marker()),false);}
  const ss=storage();ss.setItem=()=>{};const h=harness({storage:ss});await h.controller.connect(meta);assert.equal(await h.controller.execute('record_external_contact','본문'),false);assert.equal(h.posts().length,0);assert.equal(h.controller.snapshot().status,'storageerror');});
await check('support GET begins only after selected native detail ready; projection has no private metadata',async()=>{const h=harness();for(const patch of [{connection:'loading'},{detailState:'idle'},{detailState:'error'},{orderNo:null}]){await h.controller.connect({...meta,...patch});assert.equal(h.calls.length,0);}await h.controller.connect(meta);assert.equal(h.calls[0].url,'/api/admin/auth/me');assert.equal(h.calls[1].url,'/api/admin/commerce/orders/'+no+'/support?limit=20');assert.equal(h.posts().length,0);});
await check('current server viewer reads but cannot write, exact recover or resend',async()=>{const h=harness();h.setRole('viewer');await h.controller.connect(meta);assert.equal(await h.controller.execute('record_external_contact','본문'),false);assert.equal(await h.controller.retry(),false);assert.equal(await h.controller.exact(),false);assert.equal(h.posts().length,0);assert.match(ui.renderHTML(h.controller.snapshot()),/조회 전용/);});
await check('principal change denies and wipes events before write; old local role is no authority',async()=>{const h=harness();await h.controller.connect(meta);await h.controller.selectCase(ID);h.setRole('viewer');await h.controller.execute('internal_note','PRIVATE');assert.equal(h.posts().length,0);assert.equal(h.denials(),1);assert.deepEqual(h.controller.snapshot().events,[]);assert.equal(h.controller.snapshot().actor,null);});
await check('each write authenticates and persists/readbacks original marker before sending exact body',async()=>{const h=harness({post:async(cmd)=>{assert.equal(h.ss.data.size,1);const raw=[...h.ss.data.values()][0];assert(!raw.includes('PRIVATE'));assert.equal(JSON.parse(raw).operation_id,cmd.operation_id);return response(receipt(cmd));}});await h.controller.connect(meta);await h.controller.selectCase(ID);await h.controller.execute('internal_note','PRIVATE 원문');assert.equal(h.posts().length,1);const cmd=JSON.parse(h.posts()[0].init.body);assert.equal(cmd.body,'PRIVATE 원문');assert.equal(cmd.expected_revision,1);assert.equal(h.controller.snapshot().status,'confirmed');assert.equal(h.ss.data.size,0);assert.equal(h.controller.snapshot().hasRam,false);});
await check('input correction can execute after validation failure without allocating a POST attempt',async()=>{const h=harness();await h.controller.connect(meta);await h.controller.execute('record_external_contact','<bad>');assert.equal(h.posts().length,0);assert.equal(h.ss.data.size,0);assert.equal(h.controller.snapshot().status,'inputerror');assert.equal(await h.controller.execute('record_external_contact','정정 본문'),true);});
await check('double-click busy guard permits one POST and cases/latest cannot alter pending immutable body',async()=>{const d=deferred(),h=harness({post:()=>d.promise});await h.controller.connect(meta);const sending=h.controller.execute('record_external_contact','원 본문');await until(()=>h.posts().length===1);assert.equal(h.posts().length,1);assert.equal(await h.controller.execute('record_external_contact','바뀐 본문'),false);assert.equal(await h.controller.cases(),false);assert.equal(await h.controller.latest(),false);d.resolve(response(receipt(JSON.parse(h.posts()[0].init.body))));await sending;assert.equal(h.posts().length,1);});
await check('unknown network/invalid JSON/5xx keeps marker and RAM; no automatic POST, rekey or invented hash',async()=>{for(const type of ['network','html','invalid','5xx']){const h=harness({post:()=>{if(type==='network')throw Error('network');return response(type==='invalid'?{}:{},type==='5xx'?503:200,type==='html'?'text/html':'application/json');}});await h.controller.connect(meta);await h.controller.execute('record_external_contact','원 본문');const s=h.controller.snapshot();assert.equal(s.status,'unconfirmed');assert.equal(s.hasRam,true);assert.equal(s.marker.request_hash,null);assert.equal(h.posts().length,1);assert(![...h.ss.data.values()][0].includes('원 본문'));assert.equal(await h.controller.exact(),false);assert.equal(h.posts().length,1);}});
await check('explicit same-RAM resend uses byte-identical UUID and original payload; fresh current revision does not rewrite it',async()=>{let count=0;const h=harness({post:cmd=>++count===1?response({},503):response(receipt(cmd,{}, {revision:3}))});await h.controller.connect(meta);await h.controller.execute('record_external_contact','원 본문');await h.controller.latest();assert.equal(h.posts().length,1);await h.controller.retry();assert.equal(h.posts().length,2);assert.equal(h.posts()[0].init.body,h.posts()[1].init.body);assert.equal(h.controller.snapshot().current.revision,3);});
await check('reload after hashless response loses RAM and retains same marker; latest GET is not original proof',async()=>{const ss=storage(),h=harness({storage:ss,post:()=>response({},503)});await h.controller.connect(meta);await h.controller.execute('record_external_contact','원 본문');const original=[...ss.data.values()][0];h.controller.dispose();const reload=harness({storage:ss});await reload.controller.connect(meta);assert.equal(reload.controller.snapshot().hasRam,false);assert.equal(await reload.controller.retry(),false);assert.equal(await reload.controller.exact(),false);await reload.controller.latest();assert.equal(reload.controller.snapshot().status,'unconfirmed');assert.equal([...ss.data.values()][0],original);assert.equal(reload.posts().length,0);assert.match(ui.renderHTML(reload.controller.snapshot()),/본문이 보존되지 않아/);});
await check('known received hash recovery performs authenticated exact GET only and clears matching marker',async()=>{const ss=storage(),tag=await ui.scopeTag(crypto,no,ui.principal(actor()));const cmd=ui.command('internal_note',caseValue(),'확인 본문',ID);ui.markerStore(ss,tag,()=>true).put(marker({scope_tag:tag,request_hash:HASH}),null);const h=harness({storage:ss,fetch:(url,init)=>Promise.resolve(response(url==='/api/admin/auth/me'?actor():url.includes('operation_id=')?receipt(cmd):cases()))});await h.controller.connect(meta);assert.equal(h.controller.snapshot().hasRam,false);assert.equal(await h.controller.exact(),true);assert.equal(h.posts().length,0);const exact=h.calls.find(c=>c.url.includes('operation_id='));assert.equal(exact.init.method,'GET');assert.equal(exact.url,'/api/admin/commerce/orders/'+no+'/support?operation_id='+ID+'&request_hash='+HASH);assert.equal(ss.data.size,0);});
await check('cross order and actor scope tags differ; a stored tag never supplies role authority',async()=>{const p=ui.principal(actor());assert.notEqual(await ui.scopeTag(crypto,no,p),await ui.scopeTag(crypto,'ORD-EXAMPLE-02',p));assert.notEqual(await ui.scopeTag(crypto,no,p),await ui.scopeTag(crypto,no,{...p,operator_id:8}));assert.equal(await ui.scopeTag(crypto,no,p),await ui.scopeTag(crypto,no,{...p,role:'viewer'}));});
await check('late success/network failure/403 cannot deny or refill a new selected detail',async()=>{for(const kind of ['success','failure','403']){const d=deferred();let gets=0;const h=harness({fetch:(url)=>url==='/api/admin/auth/me'?Promise.resolve(response(actor())):++gets===1?d.promise:Promise.resolve(response(cases([])))});const old=h.controller.connect(meta);await until(()=>gets===1);await h.controller.connect({...meta,renderSerial:2});if(kind==='failure')d.reject(Error('old failure'));else d.resolve(response(cases(),kind==='403'?403:200));await old;assert.equal(h.controller.snapshot().status,'ready');assert.deepEqual(h.controller.snapshot().cases,[]);assert.equal(h.denials(),0);}});
await check('parent selection/loading/filter/clear cancels private body RAM and ignores late write evidence',async()=>{const d=deferred(),h=harness({post:()=>d.promise});await h.controller.connect(meta);const sending=h.controller.execute('record_external_contact','PRIVATE 原文');await until(()=>h.posts().length===1);const original=[...h.ss.data.values()][0];await h.controller.connect({...meta,detailState:'loading',renderSerial:2});d.resolve(response(receipt(JSON.parse(h.posts()[0].init.body))));await sending;assert.equal(h.controller.snapshot().hasRam,false);assert.equal(h.controller.snapshot().receipt,null);assert.equal(h.controller.snapshot().actor,null);assert.equal([...h.ss.data.values()][0],original);});
await check('current support 401/403 closes module, signals parent once and preserves recovery marker',async()=>{for(const status of [401,403]){const h=harness({post:()=>response({},status)});await h.controller.connect(meta);await h.controller.execute('record_external_contact','PRIVATE');assert.equal(h.denials(),1);assert.equal(h.controller.snapshot().status,'denied');assert.equal(h.controller.snapshot().hasRam,false);assert.equal(h.controller.snapshot().marker,null);assert.equal(h.ss.data.size,1);assert(!JSON.stringify(h.controller.snapshot()).includes('PRIVATE'));}});
await check('conflict remains uncertain original attempt and does not permit a new operation',async()=>{const h=harness({post:()=>response({},409)});await h.controller.connect(meta);await h.controller.execute('record_external_contact','원 본문');assert.equal(h.controller.snapshot().status,'conflict');const markerBefore=[...h.ss.data.values()][0];assert.equal(await h.controller.execute('record_external_contact','다른 본문'),false);assert.equal([...h.ss.data.values()][0],markerBefore);assert.equal(h.posts().length,1);});
await check('tampering with any original marker field blocks POST even if UUID matches',async()=>{const h=harness({post:()=>response({},503)});await h.controller.connect(meta);await h.controller.execute('record_external_contact','원 본문');const [key,raw]=[...h.ss.data.entries()][0];h.ss.data.set(key,JSON.stringify({...JSON.parse(raw),request_hash:HASH}));await h.controller.retry();assert.equal(h.posts().length,1);assert.equal(JSON.parse(h.ss.getItem(key)).request_hash,HASH);});
await check('only committed selected draft publishes, retaining exact reference and original draft body',async()=>{const draft=event({action:'record_reply',author_kind:'operator',actor:{kind:'operator',operator_id:7},visible:false,body:'저장 초안 본문'});const h=harness({fetch:(url,init)=>Promise.resolve(response(url==='/api/admin/auth/me'?actor():init.method==='POST'?receipt(JSON.parse(init.body)):url.includes('case_id=')?events([draft]):cases()))});await h.controller.connect(meta);await h.controller.selectCase(ID);assert.equal(await h.controller.execute('publish_customer_reply','바뀐 입력',OTHER),false);await h.controller.execute('publish_customer_reply','바뀐 입력',EV);const cmd=JSON.parse(h.posts()[0].init.body);assert.equal(cmd.reply_event_id,EV);assert(!Object.hasOwn(cmd,'body'));assert.equal(h.controller.snapshot().receipt.result.event_body,draft.body);});
await check('bounded pagination uses opaque cursor and authenticates; invalid repeated cursor removes old records',async()=>{let count=0;const h=harness({fetch:(url)=>Promise.resolve(response(url==='/api/admin/auth/me'?actor():++count===1?cases([caseValue()],'opaque_cursor'):cases([caseValue()], 'opaque_cursor')))});await h.controller.connect(meta);await h.controller.next();assert.equal(h.controller.snapshot().status,'error');assert.deepEqual(h.controller.snapshot().cases,[]);assert(!ui.renderHTML(h.controller.snapshot()).includes('페이지 기록 0개'));assert(h.calls.some(c=>c.url.endsWith('&cursor=opaque_cursor')));});
await check('failed GET and inaccessible storage are distinct from a confirmed empty page',async()=>{const ss=storage();ss.getItem=()=>{throw Error('blocked');};const blocked=harness({storage:ss});await blocked.controller.connect(meta);assert.equal(blocked.controller.snapshot().status,'storageerror');assert.equal(blocked.calls.length,1);const h=harness({fetch:url=>Promise.resolve(url==='/api/admin/auth/me'?response(actor()):response({},503))});await h.controller.connect(meta);assert.equal(h.controller.snapshot().status,'error');assert(!ui.renderHTML(h.controller.snapshot()).includes('페이지 기록 0개'));const empty=harness({fetch:url=>Promise.resolve(response(url==='/api/admin/auth/me'?actor():cases([])))});await empty.controller.connect(meta);assert(ui.renderHTML(empty.controller.snapshot()).includes('페이지 기록 0개'));});
await check('render escaping and labels preserve publication, transmission, resolution and refund boundaries',()=>{const s={status:'confirmed',busy:false,actor:{role:'operator'},cases:[],current:caseValue({revision:3}),events:[],receipt:receipt(ui.command('close',caseValue(),'종결',ID)).operation_result,marker:null,mode:'events',next:null,page:0};const html=ui.renderHTML(s,'internal_note','</textarea><script>PRIVATE</script>');assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'));for(const text of ['당시 종결 / 변경 기준 2','현재 문의 · 진행 중 / 변경 기준 3','실제 해결 근거 미확인','실제 전달·열람·해결은 각각 다릅니다','외부 발송은 시도하지 않습니다'])assert(html.includes(text));});
await check('DOM adapter preserves keyboard mode focus, clears old mode text, closes on parent lifecycle and detaches on dispose',async()=>{const d=domHarness();const module=ui.mount(d.root,{crypto,storage:storage(),fetch:async(url)=>response(url==='/api/admin/auth/me'?actor():url.includes('case_id=')?events():cases())});await module.controller.connect(meta);await module.controller.selectCase(ID);const input=d.slot.querySelector('#acs-body');input.value='PRIVATE 이전 내부 메모';d.dispatch('input',input);const button=d.slot.querySelector('[data-acs-action="record_reply"]');button.focus();d.dispatch('click',button);assert.equal(d.doc.activeElement.dataset.acsAction,'record_reply');assert(!d.slot.innerHTML.includes('PRIVATE'));d.notify({...meta,detailState:'loading',renderSerial:2});assert.equal(module.controller.snapshot().hasRam,false);assert.equal(module.controller.snapshot().actor,null);assert(!d.slot.innerHTML.includes('가상 문의'));module.dispose();d.notify(meta);assert.equal(module.controller.snapshot().status,'disconnected');assert.equal(d.slot.innerHTML,'');});
await check('mounted support auth denial disposes original GET adapter and denies original renderer',async()=>{const d=domHarness();const module=ui.mount(d.root,{crypto,storage:storage(),fetch:async(url)=>response(url==='/api/admin/auth/me'?actor():{},url==='/api/admin/auth/me'?200:403)});await module.controller.connect(meta);assert.equal(d.root.transportDisposed,true);assert.equal(d.root.denied,true);assert.equal(module.controller.snapshot().actor,null);assert.equal(module.controller.snapshot().events.length,0);assert(!d.slot.innerHTML.includes('PRIVATE'));});
await check('support source uses no localStorage, provider/money or automatic operation rekey recovery',()=>{const source=fs.readFileSync(path.join(__dirname,'../mockups/shared/admin-commerce-support.js'),'utf8');assert(!/localStorage|location\.|console\.|provider_token|approved_amount|setOnSelect/.test(source));assert.equal((source.match(/randomUUID\(/g)||[]).length,1);assert(!source.includes('setInterval'));});
console.log(checks+' support UI regression groups passed');}
run().catch(e=>{console.error(e);process.exitCode=1;});
