// Isolated renderer/event regression. Actual browser DOM/layout checks are separate.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ui=require('../mockups/shared/admin-commerce-orders.js');
const fixtureOrders=()=>[
  {commerce_version:'commerce_v1',order_no:'ORD-EXAMPLE-01',order_state:'접수',checkout_state:'unknown',payment_state:'unknown',allocation_state:'protected',refund_state:'none',total:'9007199254740993',currency:'KRW',expires_at:1791200000,lines:[{line_id:'line-1',name:'격리 검증용 상품 A',qty:1,unit_amount:'9007199254740993'}],reason_codes:['payment_result_unknown','allocation_protected'],capabilities:{approve:false,cancel:false,partial_cancel:false,guest_checkout:true}},
  {commerce_version:'commerce_v1',order_no:'ORD-EXAMPLE-02',order_state:'결제완료',checkout_state:'paid',payment_state:'confirmed',allocation_state:'allocated',refund_state:'requested',total:'0',currency:'KRW',expires_at:1791200000,lines:[{line_id:'line-2',name:'격리 검증용 상품 B',qty:2,unit_amount:'0'}],reason_codes:['refund_requested'],capabilities:{approve:false,cancel:true,partial_cancel:true,guest_checkout:true}}
];
function harness(){
  const elements=new Map(),events={},classes=new Set();
  const filters=['all','payment','fulfillment','refund'].map(value=>({dataset:{filter:value},disabled:true,setAttribute(k,v){this[k]=v;}}));
  const element=id=>{if(!elements.has(id))elements.set(id,{id,dataset:{},disabled:false,value:'',textContent:'',innerHTML:'',events:{},focus(){root.focused=id;root.focusCalls.push(id);},addEventListener(type,fn){this.events[type]=fn;}});return elements.get(id);};
  const root={focused:null,focusCalls:[],classList:{add:x=>classes.add(x),remove:x=>classes.delete(x)},querySelector:s=>{if(s.startsWith('#'))return element(s.slice(1));const match=s.match(/^\[data-order-index="(\d+)"\]$/);return match&&element('aco-rows').innerHTML.includes('data-order-index="'+match[1]+'"')?element('order-'+match[1]):null;},querySelectorAll:()=>filters,addEventListener(t,f){events[t]=f;}};
  const controller=ui.mount(root);
  const click=button=>events.click({target:{closest:()=>button}});
  const select=index=>click({disabled:false,dataset:{orderIndex:String(index)}});
  const filter=value=>click({disabled:false,dataset:{filter:value}});
  const load=rows=>controller.receive(controller.begin(),rows);
  return {root,element,controller,select,filter,click,load,classes,filters};
}
function run(){let checks=0;const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
check('disconnected, loading, error and empty are distinct and never show stale success',()=>{const h=harness();assert.match(h.element('aco-rows').innerHTML,/연결 필요/);const token=h.controller.begin();assert.match(h.element('aco-rows').innerHTML,/불러오는 중/);h.controller.fail(token);assert.match(h.element('aco-rows').innerHTML,/조회 실패/);h.load([]);assert.match(h.element('aco-rows').innerHTML,/조회 결과 주문 없음/);assert(!h.element('aco-connection').textContent.includes('연결되지'));});
check('one order row carries multiple reasons without fabricated global task counts',()=>{const h=harness();h.load(fixtureOrders());const rows=h.element('aco-rows').innerHTML;assert.equal((rows.match(/class="aco-row"/g)||[]).length,2);assert(rows.includes('payment_result_unknown'));assert(rows.includes('allocation_protected'));assert.match(h.element('aco-count').textContent,/전체 주문 건수 미확인/);});
check('decimal money above JS precision and BIGINT max displays losslessly; genuine zero remains zero',()=>{assert.equal(ui.money('9007199254740993'),'9,007,199,254,740,993원');assert.equal(ui.money('9223372036854775807'),'9,223,372,036,854,775,807원');assert.equal(ui.money('0'),'0원');for(const amount of [null,undefined,0,9007199254740992,'01','-1','1.5','1e3','9223372036854775808','9'.repeat(100)])assert.equal(ui.money(amount),'금액 확인 필요');});
check('invalid money, version, quantity, enum or inconsistent state removes confirmed detail',()=>{for(const patch of [{total:null},{total:1},{total:'01'},{commerce_version:'v2'},{payment_state:'new'},{checkout_state:'paid',payment_state:'unknown'},{allocation_state:'allocated',payment_state:'unknown'},{expires_at:NaN},{capabilities:{approve:true}}]){const h=harness();h.load(fixtureOrders());h.select(1);assert.match(h.element('aco-detail').innerHTML,/승인 확정/);assert.equal(h.load([{...fixtureOrders()[0],...patch}]),false);assert(!h.element('aco-detail').innerHTML.includes('승인 확정'));assert.match(h.element('aco-rows').innerHTML,/응답 확인 필요/);}for(const qty of [true,0,1.5,2147483648]){const row=fixtureOrders()[0];row.lines[0].qty=qty;assert.throws(()=>ui.project(row));}});
check('missing schema fields, coerced enums, empty lines, duplicate orders or reasons fail closed',()=>{for(const input of [null,{},[{}],[fixtureOrders()[0],fixtureOrders()[0]],[{...fixtureOrders()[0],lines:[]}],[{...fixtureOrders()[0],reason_codes:['x','x']}],[{...fixtureOrders()[0],payment_state:['unknown']}]]){const h=harness();assert.equal(h.load(input),false);assert.match(h.element('aco-rows').innerHTML,/응답 확인 필요/);}});
check('public allowlist drops PII, provider values, client hrefs and capabilities',()=>{const row={...fixtureOrders()[0],owner_hash:'secret',shipping:{phone:'PRIVATE'},provider_token:'PRIVATE',environment:'live',reconcile_url:'https://evil.test',created_at:'invented',capabilities:{approve:true,cancel:true,partial_cancel:true,guest_checkout:true}};const p=ui.project(row);assert(!JSON.stringify(p).includes('PRIVATE'));for(const key of ['capabilities','environment','shipping','reconcile_url','created_at'])assert(!Object.hasOwn(p,key));});
check('common capabilities never enable operator actions or infer PG evidence',()=>{const h=harness();h.load(fixtureOrders());h.select(1);const html=h.element('aco-detail').innerHTML;assert.equal((html.match(/<button type="button" disabled>/g)||[]).length,3);assert.match(html,/PG 근거/);assert.match(html,/실행 환경 · 미확인/);assert.match(html,/실물 회수 · 미확인/);assert(!html.includes('배송 완료'));});
check('order, payment, allocation and refund remain distinct; no charge totals are computed',()=>{const h=harness();h.load(fixtureOrders());h.select(0);const html=h.element('aco-detail').innerHTML;for(const label of ['주문서','결제','재고 배정','환불 자금','예약 보호','배송비·추가 비용 내역 미확인','9,007,199,254,740,993원'])assert(html.includes(label));h.select(1);assert.match(h.element('aco-detail').innerHTML,/요청 접수/);assert(!h.element('aco-detail').innerHTML.includes('자금 환불 완료'));});
check('all displayed text is escaped and order identity is never placed in a selector or URL',()=>{const row=fixtureOrders()[0];row.order_no='</button><img src=x onerror=alert(1)>';row.lines[0].name='<script>secret</script>';row.reason_codes=['<svg/onload=alert(1)>'];const h=harness();h.load([row]);h.select(0);const html=h.element('aco-rows').innerHTML+h.element('aco-detail').innerHTML;assert(!html.includes('<img'));assert(!html.includes('<script>'));assert(!html.includes('<svg'));assert(html.includes('&lt;script&gt;'));assert(html.includes('data-order-index="0"'));});
check('search and local filters select visible orders only, clear old detail and preserve one-row identity',()=>{const h=harness();h.load(fixtureOrders());h.select(0);assert(h.classes.has('show-detail'));h.filter('refund');assert(!h.element('aco-rows').innerHTML.includes('ORD-EXAMPLE-01'));assert(!h.element('aco-detail').innerHTML.includes('ORD-EXAMPLE-01'));h.select(0);assert(!h.classes.has('show-detail'));h.select(1);assert(h.classes.has('show-detail'));h.click({id:'aco-back',disabled:false,dataset:{}});assert(!h.classes.has('show-detail'));h.element('aco-search').value='missing';h.element('aco-search').events.input();assert.match(h.element('aco-rows').innerHTML,/現在|현재 조건/);assert(!h.element('aco-detail').innerHTML.includes('ORD-EXAMPLE'));});
check('detail selection hands focus to visible heading; back restores same row with search fallback',()=>{const h=harness();h.load(fixtureOrders());h.select(1);assert.equal(h.root.focused,'aco-detail-title');assert(h.classes.has('show-detail'));h.click({id:'aco-back',disabled:false,dataset:{}});assert.equal(h.root.focused,'order-1');assert(!h.classes.has('show-detail'));h.select(1);h.element('aco-rows').innerHTML='';h.click({id:'aco-back',disabled:false,dataset:{}});assert.equal(h.root.focused,'aco-search');});
check('query/filter rendering leaves active input focus alone; invalid or stale selection cannot move focus',()=>{const h=harness();h.load(fixtureOrders());h.element('aco-search').focus();h.element('aco-search').value='02';h.element('aco-search').events.input();assert.equal(h.root.focused,'aco-search');h.filter('refund');assert.equal(h.root.focused,'aco-search');h.select(0);assert.equal(h.root.focused,'aco-search');h.select('0"]');assert.equal(h.root.focused,'aco-search');h.controller.disconnect();h.select(1);assert.equal(h.root.focused,'aco-search');});
check('late success or failure cannot replace the latest load and disconnect invalidates tokens',()=>{const h=harness();const a=h.controller.begin(),b=h.controller.begin();assert.equal(h.controller.receive(a,fixtureOrders()),false);assert.equal(h.controller.fail(a),false);assert(h.controller.receive(b,fixtureOrders()));h.select(1);h.controller.disconnect();assert(!h.element('aco-detail').innerHTML.includes('승인 확정'));assert.equal(h.controller.receive(b,fixtureOrders()),false);assert.match(h.element('aco-rows').innerHTML,/연결 필요/);});
check('projection copies DTO values so later mutation cannot change selected evidence',()=>{const rows=fixtureOrders(),h=harness();h.load(rows);rows[0].total='1';rows[0].lines[0].name='changed';rows[0].reason_codes.push('changed');h.select(0);assert.match(h.element('aco-detail').innerHTML,/9,007,199,254,740,993원/);assert(!h.element('aco-detail').innerHTML.includes('changed'));});
check('unknown payment gets attention priority while maintaining one row per order',()=>{const h=harness();h.load(fixtureOrders().reverse());const html=h.element('aco-rows').innerHTML;assert(html.indexOf('ORD-EXAMPLE-01')<html.indexOf('ORD-EXAMPLE-02'));assert.equal((html.match(/class="aco-row"/g)||[]).length,2);});
check('production renderer contains no transport, storage, fixtures, endpoint or operational form',()=>{const source=fs.readFileSync(path.join(__dirname,'../mockups/shared/admin-commerce-orders.js'),'utf8');assert(!/\bfetch\s*\(|XMLHttpRequest|localStorage|sessionStorage|\/api\/|ORD-EXAMPLE/.test(source));const template=fs.readFileSync(path.join(__dirname,'../templates/admin/commerce_orders.html.j2'),'utf8');assert(template.includes('admin/_admin2_shell.html.j2'));assert(!/ORD-EXAMPLE|<form|mock|fixture/i.test(template));});
function adminDetail(row=fixtureOrders()[0]){return {...row,checked_at:Date.UTC(2026,9,5,3,4,5)/1000,basis_state:'unconfirmed',basis_id:null,approved_amount:row.payment_state==='confirmed'?row.total:'0',refunded_amount:'0',refundable_amount:row.payment_state==='confirmed'?row.total:'0',provider_environment:'unknown',verification_state:'unknown',provider_checked_at:null,actions:Object.fromEntries(['reconcile','cancel_payment','advance_fulfillment','return_stock'].map(key=>[key,{allowed:false,reason:'route_unavailable',expected_basis:null}]))};}
function selectedDetail(row){const h=harness();h.load([row]);h.select(0);const token=h.controller.beginDetail(row.order_no);assert(h.controller.receiveDetail(token,row));return h;}
check('list fallback never turns missing internal amounts or PG observation into zero',()=>{const h=harness();h.load(fixtureOrders());h.select(1);const html=h.element('aco-detail').innerHTML;assert.match(html,/상세 원장 근거 미연결/);for(const label of ['내부 승인액','내부 환불액','내부 환불가능액'])assert(html.includes('<th scope="row">'+label+'</th><td>미확인</td>'));assert(html.includes('<th scope="row">서버 주문 총액</th><td>0원</td>'));assert.match(html,/상세 원장 금액과 확인 시각은 아직 연결되지/);});
check('ready unknown detail shows genuine validated zero separately and reason/next action without comparison verdict',()=>{const h=selectedDetail(adminDetail()),html=h.element('aco-detail').innerHTML;for(const label of ['내부 승인액','내부 환불액','내부 환불가능액'])assert(html.includes('<th scope="row">'+label+'</th><td>0원</td>'));for(const label of ['이유','안전한 다음 조치','결과 확인 필요','비교 판정 미연결','PG 정산·은행 입금 근거 미연결'])assert(html.includes(label));assert.match(html,/재결제나 수동 성공 처리를 하지 않습니다/);assert.equal((html.match(/<button type="button" disabled>/g)||[]).length,3);});
check('large approved refunded and refundable values stay distinct without summed net or guessed PG amount',()=>{const row=adminDetail(fixtureOrders()[1]);row.total='9223372036854775807';row.lines[0].unit_amount=row.total;row.approved_amount=row.total;row.refunded_amount='9007199254740993';row.refundable_amount='9214364837600034814';const html=selectedDetail(row).element('aco-detail').innerHTML;for(const value of ['9,223,372,036,854,775,807원','9,007,199,254,740,993원','9,214,364,837,600,034,814원'])assert(html.includes(value));assert(!html.includes('순액'));assert(!html.includes('차액'));assert.match(html,/PG 금액·비교 판정·원문·참조·사건 이력은 미연결/);});
check('order query time and PG verification time use separate genuine timestamps; null is unknown',()=>{const row=adminDetail();row.provider_checked_at=row.checked_at-60;const html=selectedDetail(row).element('aco-detail').innerHTML;assert.match(html,/주문 조회 시각<\/span><time>[^<]*12:04:05/);assert.match(html,/PG 검증 시각<\/span><time>[^<]*12:03:05/);assert.match(html,/한국시간/);row.provider_checked_at=null;const unknown=selectedDetail(row).element('aco-detail').innerHTML;assert.match(unknown,/PG 검증 시각<\/span><time>미확인<\/time>/);assert.match(unknown,/주문 조회 시각<\/span><time>[^<]*12:04:05/);});
check('unrenderable valid server timestamp is unknown and never replaced by browser current time',()=>{const row=adminDetail();row.checked_at=Number.MAX_SAFE_INTEGER;const html=selectedDetail(row).element('aco-detail').innerHTML;assert.match(html,/주문 조회 시각<\/span><time>미확인/);assert.match(html,/PG 검증 시각<\/span><time>미확인/);});
check('confirmed normal payment stays confirmed while refunds distinguish cash from physical receipt',()=>{const row=adminDetail(fixtureOrders()[1]);row.refund_state='none';const normal=selectedDetail(row).element('aco-detail').innerHTML;assert.match(normal,/<strong>승인 확정 · 비교 판정 미연결<\/strong>/);assert.match(normal,/조회된 내부 결제 상태는 승인 확정입니다/);assert(!normal.includes('현재 결제 상태는 결과 확인 필요'));row.refund_state='requested';const pending=selectedDetail(row).element('aco-detail').innerHTML;assert.match(pending,/승인 확정 · 요청 접수/);assert.match(pending,/환불 자금 상태와 실물 회수는 별도로 확인/);assert(!pending.includes('자금 환불 완료'));assert.match(pending,/실물 회수 · 미확인/);});
check('detail loading/error/invalid and deny remove all previously displayed payment evidence',()=>{for(const mode of ['loading','error','invalid','deny']){const row=adminDetail(fixtureOrders()[1]);row.total='12345';row.approved_amount='12345';row.refundable_amount='12345';const h=selectedDetail(row);assert(h.element('aco-detail').innerHTML.includes('12,345원'));const token=h.controller.beginDetail(row.order_no);if(mode==='error')h.controller.failDetail(token);else if(mode==='invalid')assert.equal(h.controller.receiveDetail(token,{...row,approved_amount:null}),false);else if(mode==='deny')h.controller.deny();assert(!h.element('aco-detail').innerHTML.includes('12,345원'));assert(!h.element('aco-detail').innerHTML.includes('내부 승인액'));if(mode==='loading')assert.match(h.element('aco-detail').innerHTML,/조회 중 · 이전 원장 근거/);if(mode==='error')assert.match(h.element('aco-detail').innerHTML,/최신 원장 근거 조회 실패/);if(mode==='invalid')assert.match(h.element('aco-detail').innerHTML,/응답 계약 확인 필요/);if(mode==='deny'){assert(!h.element('aco-rows').innerHTML.includes(row.order_no));assert.match(h.element('aco-connection').textContent,/권한 확인/);}}});
check('late selected detail success/error cannot repopulate evidence or refocus after newer selection/deny',()=>{const rows=fixtureOrders(),h=harness();h.load(rows);h.select(0);const old=h.controller.beginDetail(rows[0].order_no);h.select(1);const latest=h.controller.beginDetail(rows[1].order_no);assert(h.controller.receiveDetail(latest,adminDetail(rows[1])));assert.equal(h.controller.receiveDetail(old,adminDetail()),false);assert.equal(h.controller.failDetail(old),false);assert(h.element('aco-detail').innerHTML.includes('승인 확정 · 요청 접수'));assert.deepEqual(h.root.focusCalls,['aco-detail-title','aco-detail-title']);h.controller.deny();assert.equal(h.controller.receiveDetail(latest,adminDetail(rows[1])),false);assert(!h.element('aco-detail').innerHTML.includes('원장 근거'));});
check('payment evidence explanations never interpolate private fields and original escaped DTO text stays escaped',()=>{const row=adminDetail();row.owner_key='PRIVATE';row.provider_merchant='PRIVATE';row.raw_proof='PRIVATE';row.reason_codes=['<script>PRIVATE</script>'];row.lines[0].name='<svg>fixture</svg>';const html=selectedDetail(row).element('aco-detail').innerHTML;assert(!html.includes('<script>'));assert(!html.includes('<svg>'));assert(html.includes('&lt;svg&gt;'));assert(!html.includes('provider_merchant'));assert(!html.includes('owner_key'));assert.equal((html.match(/PRIVATE/g)||[]).length,1);});
check('support detail subscription exposes only frozen lifecycle metadata and observer failure does not break old selection handler',()=>{const h=harness(),seen=[],selections=[];h.controller.setOnSelect(no=>selections.push(no));h.controller.subscribeDetail(()=>{throw Error('observer');});const stop=h.controller.subscribeDetail(s=>seen.push(s));h.load(fixtureOrders());h.select(0);const token=h.controller.beginDetail(fixtureOrders()[0].order_no);h.controller.receiveDetail(token,adminDetail());const ready=seen.at(-1);assert.deepEqual(Object.keys(ready),['orderNo','connection','detailState','generation','selection','renderSerial']);assert(Object.isFrozen(ready));assert.equal(ready.detailState,'ready');assert.equal(ready.orderNo,fixtureOrders()[0].order_no);assert.deepEqual(selections,[fixtureOrders()[0].order_no]);assert.equal((h.element('aco-detail').innerHTML.match(/id="aco-support"/g)||[]).length,1);const count=seen.length;stop();h.controller.disconnect();assert.equal(seen.length,count);});
check('support subscribers close on redraw, detail failure, back and deny without changing old order lifecycle',()=>{const h=selectedDetail(adminDetail()),seen=[];h.controller.subscribeDetail(s=>seen.push(s));let last=seen.at(-1).renderSerial;h.filter('all');assert(seen.at(-1).renderSerial>last);last=seen.at(-1).renderSerial;h.click({id:'aco-back',disabled:false,dataset:{}});assert.equal(seen.at(-1).orderNo,null);assert.equal(seen.at(-1).detailState,'idle');assert(seen.at(-1).renderSerial>last);h.select(0);const t=h.controller.beginDetail(fixtureOrders()[0].order_no);h.controller.failDetail(t);assert.equal(seen.at(-1).detailState,'error');h.controller.deny();assert.equal(seen.at(-1).orderNo,null);assert.equal(seen.at(-1).connection,'denied');});
check('fixed detail footer is cleared with the whole detail and stale detail cannot restore it',()=>{
  for(const mode of ['reload','list-error','detail-loading','detail-error','detail-invalid','deny','disconnect','empty','filtered-empty']){
    const row=adminDetail(),h=selectedDetail(row),old=h.controller.beginDetail(row.order_no);
    assert(h.controller.receiveDetail(old,row));
    assert(h.element('aco-detail').innerHTML.includes('class="aco-actions"'));
    if(mode==='detail-loading'||mode==='detail-error'||mode==='detail-invalid'){
      const latest=h.controller.beginDetail(row.order_no);
      if(mode==='detail-error')h.controller.failDetail(latest);
      if(mode==='detail-invalid')assert.equal(h.controller.receiveDetail(latest,{...row,approved_amount:null}),false);
    }else if(mode==='deny')h.controller.deny();
    else if(mode==='disconnect')h.controller.disconnect();
    else if(mode==='filtered-empty'){h.element('aco-search').value='missing';h.element('aco-search').events.input();}
    else{const token=h.controller.begin();if(mode==='list-error')h.controller.fail(token);if(mode==='empty')h.controller.receive(token,[]);}
    const cleared=h.element('aco-detail').innerHTML;
    assert(!cleared.includes('class="aco-actions"'),mode+' must remove the footer');
    assert(!cleared.includes('id="aco-support"'),mode+' must remove the old support slot');
    assert(!cleared.includes('9,007,199,254,740,993원'));
    assert.equal(h.controller.receiveDetail(old,row),false);
    assert.equal(h.controller.failDetail(old),false);
    assert.equal(h.element('aco-detail').innerHTML,cleared);
  }
});
console.log(checks+' commerce renderer regression groups passed');}
module.exports={fixtureOrders,harness};if(require.main===module)run();
