"use strict";
// Actual shell IIFE in a bounded DOM/event/storage/auth fixture. No production IO.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../mockups/shared/admin2/admin2-shell.js'),'utf8');
function harness({mode='new',width=390,saved=null,storageError=false,role='operator',name='격리 검사',authenticated=true,authError=false,oldMedia=false}={}) {
  let doc; const ids={},writes=[],reads=[],calls=[],stored=new Map(),bodyEscapes=[];
  if(saved!==null)stored.set('admin2.lnb.collapsed',saved);
  stored.set('admin2.lnb.closed',JSON.stringify(['그룹 B']));
  class Element {
    constructor(id,parent,attrs={}) {this.id=id;this.parent=parent;this.attrs={...attrs};this.children=[];this.listeners={};this.hidden=false;this.textContent='';this.scrollTop=17;this.focusOptions=null;this.classes=new Set();this.classList={toggle:(c,on)=>on?this.classes.add(c):this.classes.delete(c),remove:c=>this.classes.delete(c),contains:c=>this.classes.has(c)};if(id)ids[id]=this;if(parent)parent.children.push(this);}
    getAttribute(k){return this.attrs[k]??null;} setAttribute(k,v){this.attrs[k]=String(v);}
    addEventListener(t,f){(this.listeners[t]||=[]).push(f);} contains(n){return !!n&&(n===this||this.children.some(c=>c.contains(n)));}
    closest(s){const match=s.match(/^\[([^=\]]+)(?:="([^"]+)")?\]$/);if(s==='.a2-lnb-grp'&&this.group)return this;if(match&&this.attrs[match[1]]!==undefined&&(!match[2]||this.attrs[match[1]]===match[2]))return this;return this.parent?.closest(s)||null;}
    querySelector(s){return this.children.find(c=>c.closest(s)===c)||null;} querySelectorAll(s){return s==='.a2-lnb-grp'?groups:[];}
    focus(opts){doc.activeElement=this;this.focusOptions=opts;}
  }
  const body=new Element('body',null,{'data-admin-mode':mode}),lnb=new Element('lnb',body,{'data-keep':'1'}),brand=new Element('lnbBrand',lnb),menu=new Element('lnbMenu',lnb),link=new Element('menuLink',menu),toggle=new Element('lnbToggle',lnb,{'data-action':'toggle-lnb'}),icon=new Element('lnbToggleIcon',toggle);
  const mobile=mode==='new'?new Element('lnbMobileToggle',lnb,{'data-action':'toggle-mobile-lnb','aria-controls':'lnbMenu'}):null;
  if(mobile)new Element('lnbMobileLabel',mobile);
  const roleBox=new Element('roleBox',body),input=new Element('bodyInput',body);input.value='보존할 초안';input.selectionStart=2;input.selectionEnd=5;
  const groups=mode==='legacy'?['그룹 A','그룹 B'].map(n=>{const g=new Element('',menu,{'data-grp':n,'data-open':'y'});g.group=true;g.button=new Element('',g,{'data-action':'lnb-group','aria-expanded':'true'});return g;}):[];
  doc={body,activeElement:input,getElementById:id=>ids[id]||null,addEventListener:(t,f)=>body.addEventListener(t,f)};
  const media={matches:width<=768,listeners:[],addEventListener:oldMedia?undefined:(t,f)=>media.listeners.push(f),addListener:f=>media.listeners.push(f)};
  const win={matchMedia:q=>{assert.equal(q,'(max-width:768px)');return media;},scrollY:193};
  const sessionStorage={getItem:k=>{reads.push(k);if(storageError)throw Error('storage unavailable');return stored.get(k)??null;},setItem:(k,v)=>{if(storageError)throw Error('storage unavailable');writes.push([k,v]);stored.set(k,v);}};
  const fetch=async(url,init)=>{calls.push([url,init]);assert.equal(url,'/api/admin/auth/me');assert.equal(init.credentials,'same-origin');if(authError)throw Error('fixture auth failure');return {json:async()=>({authenticated,operator:{name,email:'fixture@example.invalid',role}})};};
  vm.runInNewContext(source,{window:win,document:doc,sessionStorage,fetch,Promise,setTimeout:()=>0},{filename:'admin2-shell.js'});
  body.addEventListener('keydown',e=>{if(e.key==='Escape')bodyEscapes.push(e.target.id);});
  function fire(target,type,key){const ev={target,key,defaultPrevented:false,stopped:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;}};for(let n=target;n;n=n.parent){for(const f of n.listeners[type]||[])f(ev);if(ev.stopped)break;}return ev;}
  function resize(w){const next=w<=768;if(next!==media.matches){media.matches=next;for(const f of media.listeners)f({matches:next});}}
  return {doc,win,lnb,brand,menu,link,toggle,icon,mobile,roleBox,input,groups,writes,reads,calls,stored,bodyEscapes,fire,resize};
}
async function run(){let count=0;async function check(name,fn){await fn();count++;console.log('PASS '+name);}
  for(const width of [390,768])for(const saved of [null,'0','1'])await check(`NEW ${width} saved=${saved} starts closed without SS overwrite`,async()=>{const h=harness({width,saved});await h.win.Admin2Shell.meReady;assert(h.menu.hidden);assert.equal(h.mobile.getAttribute('aria-expanded'),'false');assert.equal(h.brand.textContent,'팝콘 AI');assert(!h.lnb.classList.contains('collapsed'));assert.equal(h.writes.length,0);assert.equal(h.stored.get('admin2.lnb.collapsed')??null,saved);assert.equal(h.calls.length,1);});
  for(const width of [769,850,1440])for(const saved of ['0','1'])await check(`NEW desktop ${width} retains collapse=${saved}`,()=>{const h=harness({width,saved});assert(!h.menu.hidden);assert.equal(h.lnb.classList.contains('collapsed'),saved==='1');assert.equal(h.brand.textContent,saved==='1'?'팝콘':'팝콘 AI');h.fire(h.toggle,'click');assert.equal(h.stored.get('admin2.lnb.collapsed'),saved==='1'?'0':'1');assert.equal(h.writes.length,1);});
  await check('menu open/close ARIA, exact name, hidden state and original keys',()=>{const h=harness({saved:'1'});h.fire(h.mobile,'click');assert(!h.menu.hidden);assert.equal(h.mobile.getAttribute('aria-expanded'),'true');assert.equal(h.mobile.getAttribute('aria-label'),'메뉴 닫기');assert.equal(h.doc.getElementById('lnbMobileLabel').textContent,'메뉴 닫기');h.link.focus();h.fire(h.mobile,'click');assert(h.menu.hidden);assert.equal(h.doc.activeElement,h.mobile);assert.equal(h.mobile.focusOptions.preventScroll,true);assert.equal(h.writes.length,0);});
  await check('menu Escape consumes only open nav; body and closed nav Escape stay native',()=>{const h=harness();h.fire(h.mobile,'click');h.link.focus();let e=h.fire(h.link,'keydown','Escape');assert(e.defaultPrevented&&e.stopped);assert(h.menu.hidden);assert.equal(h.bodyEscapes.length,0);assert.equal(h.doc.activeElement,h.mobile);e=h.fire(h.input,'keydown','Escape');assert(!e.stopped);h.fire(h.mobile,'keydown','Escape');assert.deepEqual(h.bodyEscapes,['bodyInput','lnbMobileToggle']);h.fire(h.mobile,'click');h.fire(h.input,'keydown','Escape');assert.equal(h.bodyEscapes.length,3);assert(!h.menu.hidden);});
  await check('resize round trip restores desktop key and visible focus without body mutation',()=>{const h=harness({width:1440,saved:'1'});h.link.focus();h.resize(390);assert(h.menu.hidden);assert.equal(h.doc.activeElement,h.mobile);h.fire(h.mobile,'click');h.resize(768);assert(!h.menu.hidden);h.mobile.focus();h.resize(769);assert.equal(h.doc.activeElement,h.toggle);assert(h.toggle.focusOptions.preventScroll);assert(!h.menu.hidden);assert(h.lnb.classList.contains('collapsed'));h.resize(390);assert(h.menu.hidden);assert.equal(h.stored.get('admin2.lnb.collapsed'),'1');assert.equal(h.writes.length,0);assert.equal(h.input.value,'보존할 초안');assert.equal(h.input.selectionStart,2);assert.equal(h.win.scrollY,193);assert.equal(h.menu.scrollTop,17);});
  await check('desktop toggle focus transfers to mobile visible trigger on entry',()=>{const h=harness({width:1440,saved:'0'});h.toggle.focus();h.resize(390);assert.equal(h.doc.activeElement,h.mobile);assert.equal(h.mobile.focusOptions.preventScroll,true);assert(h.menu.hidden);assert.equal(h.writes.length,0);});
  for(const saved of [null,'0','1'])await check(`legacy mobile existing groups and persistence saved=${saved}`,()=>{const h=harness({mode:'legacy',saved});assert.equal(h.mobile,null);assert(!h.menu.hidden);assert.equal(h.lnb.classList.contains('collapsed'),saved==='1');assert.equal(h.groups[1].getAttribute('data-open'),'n');assert.equal(h.groups[1].button.getAttribute('aria-expanded'),'false');h.fire(h.groups[0].button,'click');assert.equal(h.groups[0].getAttribute('data-open'),'n');assert.equal(h.groups[0].button.getAttribute('aria-expanded'),'false');assert(JSON.parse(h.stored.get('admin2.lnb.closed')).includes('그룹 A'));assert(!h.lnb.classList.contains('collapsed'));h.resize(1440);assert.equal(h.stored.get('admin2.lnb.collapsed')??null,saved);});
  for(const mode of ['new','legacy'])await check(`${mode} storage exception preserves usable original behavior`,()=>{const h=harness({mode,storageError:true});if(mode==='new'){assert(h.menu.hidden);h.fire(h.mobile,'click');assert(!h.menu.hidden);h.resize(1440);}h.fire(h.toggle,'click');assert(h.lnb.classList.contains('collapsed'));});
  for(const role of ['viewer','operator','owner'])await check(`auth one call, role ${role}, existing exports and long name`,async()=>{const h=harness({role,name:'격리검증용아주긴계정이름0123456789'});const me=await h.win.Admin2Shell.meReady;assert.equal(me.role,role);assert(h.roleBox.textContent.startsWith(me.name));assert.equal(h.win.Admin2Shell.getMe(),me);assert.equal(h.win.Admin2Shell.canWrite('operator'),role!=='viewer');assert.equal(h.win.Admin2Shell.canWrite('owner'),role==='owner');assert.equal(h.win.Admin2Shell.isKeepClick(h.link),true);assert.equal(h.win.Admin2Shell.isKeepClick(h.input),false);assert.equal(typeof h.win.Admin2Shell.toast,'function');assert.equal(h.calls.length,1);});
  for(const options of [{authenticated:false},{authError:true}])await check(`auth denied/error is not fabricated operator ${JSON.stringify(options)}`,async()=>{const h=harness(options);assert.equal(await h.win.Admin2Shell.meReady,null);assert.equal(h.roleBox.textContent,'로그인 필요');assert.equal(h.win.Admin2Shell.canWrite(),false);assert.equal(h.calls.length,1);});
  await check('media addListener fallback closes mobile reentry',()=>{const h=harness({oldMedia:true});h.fire(h.mobile,'click');h.resize(1440);h.resize(390);assert(h.menu.hidden);});
  console.log(`PASS ${count} shell tests; only injected DOM/storage/auth fixtures`);
}
run().catch(e=>{console.error(e);process.exitCode=1;});
