// Executes the real UI script and its event handlers with isolated GET fixtures.
// Browser DOM/layout verification is separate; no DB, AI or operational writes.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../mockups/shared/parts-management.js'),'utf8');
const KEY='popcorn.parts.operations.return';
const row=code=>({product_code:code,name:'SSD '+code,slot_label:'SSD',facts:[],price:123400,management_state:'pending'});
const detail=code=>({...row(code),source_current:true,can_edit:true,usages:[],sources:[],history:[],edit_content:{facts:[],role:'original',highlights:[],cautions:[],questions:[]}});
const tick=async()=>{for(let i=0;i<4;i++)await new Promise(resolve=>setImmediate(resolve));};
const good={filters:{q:'SSD',slot:'SSD',sale:'판매중',review:'pending',owned:true,limit:20},offset:20,product_code:42,tab:'copy'};
function harness({saved=null,list=null,reply=null,brokenStorage=false,confirm=()=>true}={}){
  const focusCalls=[],elements=new Map(),rootEvents={},windowEvents={},calls=[],storage=new Map(saved==null?[]:[[KEY,typeof saved==='string'?saved:JSON.stringify(saved)]]);
  function element(id){if(!elements.has(id)){const events={};elements.set(id,{id,events,dataset:{},innerHTML:'',textContent:'',value:'',checked:false,disabled:false,children:[],classList:{values:new Set(),add(x){this.values.add(x);},remove(x){this.values.delete(x);},contains(x){return this.values.has(x);},toggle(x,on){on?this.add(x):this.remove(x);}},addEventListener(t,f){(events[t]??=[]).push(f);},querySelectorAll(){return [];},getClientRects(){return this.hidden?[]:[{}];},focus(){document.activeElement=this;focusCalls.push(this);},setAttribute(){}});}return elements.get(id);}
  const root=element('root');root.addEventListener=(t,f)=>(rootEvents[t]??=[]).push(f);
  const slotButtons=['','CPU','MB','RAM','GPU','CASE','COOLER','PSU','SSD'].map(slot=>({dataset:{slot},setAttribute(){},classList:{toggle(){}}}));
  const document={activeElement:null,getElementById:element,querySelector:()=>root,querySelectorAll:s=>s==='.pm-slots button'?slotButtons:[]};
  // Rows are replaced by innerHTML, matching the focus loss in the real browser.
  let rowButtons=[],rowsHTML='';
  const rows=element('pm-rows');
  Object.defineProperty(rows,'innerHTML',{get:()=>rowsHTML,set:html=>{
    if(rowButtons.includes(document.activeElement))document.activeElement=null;
    rowsHTML=html;rowButtons=Array.from(html.matchAll(/data-open="(\d+)"/g),m=>({
      dataset:{open:m[1]},disabled:false,hidden:false,hasAttribute:()=>false,
      getClientRects(){return this.hidden?[]:[{}];},
      focus(){document.activeElement=this;focusCalls.push(this);}
    }));
  }});
  rows.querySelectorAll=s=>s==='button[data-open]'?rowButtons:[];
  element('pm-q');document.activeElement=element('pm-q');
  const sessionStorage={getItem:k=>{if(brokenStorage)throw Error('denied');return storage.get(k)||null;},removeItem:k=>storage.delete(k),setItem:(k,v)=>{if(brokenStorage)throw Error('denied');storage.set(k,v);}};
  const context={document,window:{addEventListener:(t,f)=>(windowEvents[t]??=[]).push(f)},sessionStorage,localStorage:{getItem:()=>null,setItem(){}},URL,URLSearchParams,setTimeout,clearTimeout,confirm,structuredClone,fetch:async(url,options)=>{calls.push({url,options});let d;if(reply)d=await reply(url,options,calls.length);if(d===undefined)d=url.includes('?')?(list||{items:[row(1),row(2)],total:2,can_edit:true}):detail(Number(url.split('/').at(-1)));return {ok:true,json:async()=>d};}};
  vm.runInNewContext(source,context);
  async function click({button=null,link=null}={}){const event={prevented:false,preventDefault(){this.prevented=true;},target:{closest:s=>s==='button'?button:s==='a[data-operation]'?link:null}};for(const handler of rootEvents.click||[])await handler(event);return event;}
  function button(id,dataset={}){return {id,dataset,disabled:false,hasAttribute:()=>false};}
  async function emit(type,event={}){for(const handler of windowEvents[type]||[])await handler(event);await tick();}
  async function submit(){for(const handler of rootEvents.submit||[])await handler({target:{id:'pm-edit'},preventDefault(){}});}
  return {elements,element,storage,calls,click,button,emit,submit,windowEvents,document,focusCalls,rows:()=>rowButtons};
}
let checks=0;function check(name,fn){return Promise.resolve().then(fn).then(()=>{checks++;console.log('PASS '+name);});}
(async()=>{
await check('links keep supported product identity and label generic lists honestly',async()=>{const h=harness();await tick();const html=h.element('pm-detail').innerHTML;assert(html.includes('reviews?admin=new&amp;keyword=1&amp;status='));assert(html.includes('sourcing?admin=new&amp;product_code=1'));assert(html.includes('stock-inbound?admin=new&amp;product_code=1'));assert(html.includes('판매가 목록'));assert(html.includes('가격 이력 목록'));assert(!html.includes('sale-price?admin=new&amp;product_code'));assert(html.includes('123,400원'));assert(html.includes('data-tab="facts"'));assert(html.includes('data-tab="usage"'));});
await check('operation click stores only validated page state and returns to selected tab',async()=>{const h=harness({saved:good,list:{items:[row(41),row(42)],total:50,can_edit:true}});await tick();assert(h.calls[0].url.includes('offset=20'));assert(h.calls[1].url.endsWith('/42'));assert(h.element('pm-detail').innerHTML.includes('data-tab="copy" class="active"'));await h.click({link:{}});const state=JSON.parse(h.storage.get(KEY));assert.deepEqual(state,good);assert.deepEqual(Object.keys(state).sort(),['filters','offset','product_code','tab']);assert(!state.filters.returnUrl);});
await check('untrusted storage cannot inject navigation or query selectors',async()=>{const bad=[null,[],{},'{', {...good,product_code:-1},{...good,product_code:1.5},{...good,product_code:Number.MAX_SAFE_INTEGER+1},{...good,offset:-20},{...good,offset:21},{...good,offset:1e12},{...good,tab:'__proto__'},{...good,tab:'<img>'},...['q','slot','sale','review','owned','limit'].map(k=>({...good,filters:{...good.filters,[k]:k==='q'?'x'.repeat(101):k==='owned'?'true':k==='limit'?40:'https://evil.test'}}))];for(const saved of bad){const h=harness({saved});await tick();assert(h.calls[0].url.includes('offset=0'));assert(h.calls[1].url.endsWith('/1'));assert(!h.element('pm-detail').innerHTML.includes('evil.test'));}});
await check('missing selected part falls back; page bounds clamp; empty result has no links',async()=>{const h=harness({saved:good,list:{items:[row(41)],total:50,can_edit:true}});await tick();assert(h.calls[1].url.endsWith('/41'));assert(h.element('pm-detail').innerHTML.includes('data-tab="facts" class="active"'));const empty=harness({saved:good,list:{items:[],total:0,can_edit:true}});await tick();assert.equal(empty.calls.length,2);assert(empty.calls[1].url.includes('offset=0'));assert(!empty.element('pm-detail').innerHTML.includes('data-operation'));});
await check('editing prevents stale links and BFCache refresh without losing edit inputs',async()=>{const h=harness();await tick();await h.click({button:h.button('pm-edit-start')});h.element('pm-edit-role').value='unsaved text';const count=h.calls.length;assert(!h.element('pm-detail').innerHTML.includes('data-operation'));assert(h.element('pm-detail').innerHTML.includes('aria-disabled="true"'));const e=await h.click({link:{}});assert(e.prevented);await h.emit('pageshow',{persisted:true});assert.equal(h.calls.length,count);assert.equal(h.element('pm-edit-role').value,'unsaved text');assert(!h.storage.has(KEY));});
await check('busy AI request blocks operations without changing the AI save contract',async()=>{let release;const gate=new Promise(r=>release=r);const h=harness({reply:async(url,opts)=>url.endsWith('/ai-proposals')?gate:undefined});await tick();const run=h.click({button:h.button('pm-ai')});await tick();assert(!h.element('pm-detail').innerHTML.includes('data-operation'));const e=await h.click({link:{}});assert(e.prevented);release({basis:'new',changes:[],notes:[],model:'fixture'});await run;assert.equal(h.calls.at(-1).options.method,'POST');assert(h.calls.at(-1).url.endsWith('/ai-proposals'));});
await check('BFCache return refreshes GET evidence and restores tab; normal pageshow does not repeat',async()=>{const h=harness();await tick();await h.click({button:h.button('',{open:'2'})});await h.click({button:h.button('',{tab:'sources'})});await h.emit('pagehide');const count=h.calls.length;await h.emit('pageshow',{persisted:false});assert.equal(h.calls.length,count);await h.emit('pageshow',{persisted:true});assert.equal(h.calls.length,count+2);assert(h.calls.at(-1).url.endsWith('/2'));assert(h.element('pm-detail').innerHTML.includes('data-tab="sources" class="active"'));assert(!h.storage.has(KEY));});
await check('late detail cannot replace a newly selected part',async()=>{let release;const late=new Promise(r=>release=r);const h=harness({reply:url=>url.endsWith('/1')?late:undefined});await tick();await h.click({button:h.button('',{open:'2'})});release(detail(1));await tick();assert(h.element('pm-detail').innerHTML.includes('코드 2'));assert(!h.element('pm-detail').innerHTML.includes('keyword=1'));});
await check('GET failure removes stale operations and mismatched identity is rejected',async()=>{const h=harness({reply:()=>{throw Error('fixture failure');}});await tick();assert(h.element('pm-count').textContent==='불러오기 실패');assert(!h.element('pm-detail').innerHTML.includes('data-operation'));const mismatch=harness({reply:url=>url.endsWith('/1')?detail(99):undefined});await tick();assert(mismatch.element('pm-detail').innerHTML.includes('상세 불러오기 실패'));assert(!mismatch.element('pm-detail').innerHTML.includes('data-operation'));});
await check('session storage unavailable keeps normal read flow',async()=>{const h=harness({brokenStorage:true});await tick();assert(h.element('pm-detail').innerHTML.includes('data-operation'));await h.click({link:{}});assert.equal(h.calls.length,2);});

await check('detail heading is a stable programmatic focus target outside replaced content',()=>{const template=fs.readFileSync(require('node:path').join(__dirname,'../templates/admin/part_explanations.html.j2'),'utf8');assert(template.includes('<h2 id="pm-detail-title" tabindex="-1">부품 상세</h2>'));assert(template.indexOf('id="pm-detail-title"')<template.indexOf('id="pm-detail"'));});
await check('explicit row and queue activation focuses heading once; back restores a current row',async()=>{const h=harness();await tick();const old=h.rows()[1];old.focus();await h.click({button:old});assert.equal(h.document.activeElement,h.element('pm-detail-title'));assert.equal(h.focusCalls.filter(x=>x.id==='pm-detail-title').length,1);assert(!h.rows().includes(old));await h.click({button:h.button('pm-back')});assert.equal(h.document.activeElement,h.rows()[1]);assert.equal(h.document.activeElement.dataset.open,'2');await h.click({button:h.button('',{queue:'1'})});assert.equal(h.document.activeElement,h.element('pm-detail-title'));await h.click({button:h.button('pm-back')});assert.equal(h.document.activeElement,h.rows()[0]);});
await check('back uses search when the selected row is absent, hidden or disabled',async()=>{for(const kind of ['absent','hidden','disabled']){const h=harness();await tick();await h.click({button:h.button('',{open:kind==='absent'?'99':'2'})});if(kind!=='absent')h.rows()[1][kind]=true;await h.click({button:h.button('pm-back')});assert.equal(h.document.activeElement,h.element('pm-q'),kind);}});
await check('initial load, return restore, filter, paging and BFCache refresh do not steal focus',async()=>{for(const saved of [null,good]){const h=harness({saved,list:{items:[row(41),row(42)],total:50,can_edit:true}});await tick();assert.equal(h.focusCalls.length,0);await h.click({button:h.button('',{slot:'SSD'})});await h.click({button:h.button('pm-next')});await h.emit('pagehide');await h.emit('pageshow',{persisted:true});assert.equal(h.focusCalls.length,0);assert.equal(h.document.activeElement,h.element('pm-q'));}});
await check('back during pending detail and error responses never reclaims heading focus',async()=>{for(const fail of [false,true]){let release,reject;const gate=new Promise((a,b)=>{release=a;reject=b;});const h=harness({reply:url=>url.endsWith('/2')?gate:undefined});await tick();const opening=h.click({button:h.rows()[1]});assert.equal(h.document.activeElement,h.element('pm-detail-title'));await h.click({button:h.button('pm-back')});const selected=h.document.activeElement,count=h.focusCalls.length;fail?reject(Error('fixture detail failure')):release(detail(2));await opening;assert.equal(h.document.activeElement,selected);assert.equal(h.focusCalls.length,count);assert(!h.element('root').classList.contains('show-detail'));if(fail)assert(h.element('pm-detail').innerHTML.includes('상세 불러오기 실패'));}});
await check('rapid selections keep latest return row and responses do not steal a later focus',async()=>{let release;const gate=new Promise(r=>release=r);const h=harness({reply:(url,opts,n)=>n>2&&url.endsWith('/1')?gate:undefined});await tick();const opening=h.click({button:h.rows()[0]});await h.click({button:h.rows()[1]});h.element('pm-back').focus();const count=h.focusCalls.length;release(detail(1));await opening;assert.equal(h.document.activeElement,h.element('pm-back'));assert.equal(h.focusCalls.length,count);assert(h.element('pm-detail').innerHTML.includes('코드 2'));await h.click({button:h.button('pm-back')});assert.equal(h.document.activeElement.dataset.open,'2');});
await check('cancelled edit navigation and busy work preserve focus boundaries',async()=>{const h=harness({confirm:()=>false});await tick();await h.click({button:h.button('pm-edit-start')});h.element('pm-edit-role').focus();await h.click({button:h.rows()[1]});assert.equal(h.document.activeElement,h.element('pm-edit-role'));assert.equal(h.focusCalls.length,1);let release;const gate=new Promise(r=>release=r);const busy=harness({reply:url=>url.endsWith('/ai-proposals')?gate:undefined});await tick();const generating=busy.click({button:busy.button('pm-ai')});await tick();busy.element('pm-back').focus();await busy.click({button:busy.rows()[1]});await busy.click({button:busy.button('pm-back')});assert.equal(busy.focusCalls.length,1);release({basis:'new',changes:[],notes:[],model:'fixture'});await generating;});
await check('save requery uses the existing PUT and GET contract without taking focus',async()=>{const h=harness({reply:(url,options)=>options.method==='PUT'?{changed:false,affected:[]}:undefined});await tick();await h.click({button:h.button('pm-edit-start')});h.element('pm-evidence').value='fixture evidence';h.element('pm-evidence').focus();const count=h.focusCalls.length;await h.submit();assert.equal(h.focusCalls.length,count);assert.equal(h.calls[2].options.method,'PUT');assert.equal(h.calls[2].url,'/api/admin/part-workspace/1');assert(h.calls[3].url.includes('?'));assert.equal(h.calls[4].url,'/api/admin/part-workspace/1');});
console.log(checks+' operation/return event regression groups passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
