const test=require('node:test');
const assert=require('node:assert/strict');
const {createController,savedBlockers,restoreBlockers}=require('../mockups/shared/admin2/sale-price-new.js');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};};
const detail=(code,price=100,locked=false)=>({product_code:code,sale_price:price,locked,mall:{known:true,price:120},history:[]});
function setup(){const reads=[],writes=[];const c=createController({get:url=>{const d=deferred();reads.push({url,...d});return d.promise;},post:(url,payload)=>{const d=deferred();writes.push({url,payload,...d});return d.promise;}},()=>{});c.permission(true);return {c,reads,writes};}
test('A→B→A discards first A even when product code matches again',async()=>{const {c,reads}=setup();const a1=c.select(1),b=c.select(2),a2=c.select(1);reads[2].resolve(detail(1,300));await a2;reads[0].resolve(detail(1,100));reads[1].resolve(detail(2));await Promise.all([a1,b]);assert.equal(c.record(1).detail.sale_price,300);assert.equal(c.state.selected,1);});
test('write target stays fixed after selection moves; duplicate write blocked',async()=>{const {c,reads,writes}=setup();let p=c.select(1);reads[0].resolve(detail(1));await p;const save=c.write('match');p=c.select(2);reads[1].resolve(detail(2));await p;await c.write('lock');assert.equal(writes.length,1);assert.equal(writes[0].url,'/api/admin/sale-price/1/match');assert.deepEqual(writes[0].payload,{mall_price:120});writes[0].resolve({ok:true});await save;assert.equal(c.record(1).phase,'refreshing');assert.equal(c.record(2).detail.product_code,2);});
test('success + GET failure blocks all writes across leaving and returning; GET recovery permits writes',async()=>{const {c,reads,writes}=setup();let p=c.select(1);reads[0].resolve(detail(1));await p;const save=c.write('lock');writes[0].resolve({ok:true});await new Promise(r=>setImmediate(r));reads.find(x=>x.url.endsWith('/summary')).resolve({queue:[]});reads[2].reject(new Error('read failed'));await save;assert.equal(c.record(1).phase,'refresh_failed');assert.equal(c.allowed(c.record(1)),false);c.back();p=c.select(1);reads[3].reject(new Error('still failed'));await p;assert.equal(c.record(1).phase,'refresh_failed');await c.write('match');assert.equal(writes.length,1);p=c.read();reads[4].resolve(detail(1,120,true));await p;assert.equal(c.record(1).phase,'ready');assert.equal(c.allowed(c.record(1)),true);});
test('network ambiguity remains blocked after fresh GET and selection round trip',async()=>{const {c,reads,writes}=setup();let p=c.select(1);reads[0].resolve(detail(1));await p;const save=c.write('match');writes[0].reject(new TypeError('network'));await save;assert.equal(c.record(1).phase,'uncertain');p=c.read();reads[1].resolve(detail(1,120));await p;c.back();p=c.select(1);reads[2].resolve(detail(1,120));await p;assert.equal(c.record(1).unresolved,true);assert.equal(c.allowed(c.record(1)),false);await c.write('lock');assert.equal(writes.length,1);});
test('initial detail read failure cannot write; null current price can still be locked',async()=>{const {c,reads,writes}=setup();let p=c.select(1);reads[0].reject(new Error('read'));await p;await c.write('lock');assert.equal(writes.length,0);p=c.read();reads[1].resolve(detail(1,null,false));await p;const lock=c.write('lock');assert.deepEqual(writes[0].payload,{});writes[0].resolve({ok:true});await new Promise(r=>setImmediate(r));reads[2].resolve({queue:[]});reads[3].resolve(detail(1,null,true));await lock;assert.equal(c.record(1).detail.sale_price,null);});
test('permission rejection and conflicts are distinct; conflict requires fresh read',async()=>{for(const status of [403,409]){const {c,reads,writes}=setup();let p=c.select(1);reads[0].resolve(detail(1));await p;const save=c.write('lock');writes[0].reject(Object.assign(new Error('denied'),{status}));await save;assert.equal(c.record(1).phase,status===403?'permission':'conflict');assert.equal(c.allowed(c.record(1)),false);p=c.read();reads[1].resolve(detail(1));await p;assert.equal(c.allowed(c.record(1)),status===409);}});
test('locked match requires a second confirmation; null lock payload preserves existing policy',async()=>{const {c,reads,writes}=setup();let p=c.select(1);reads[0].resolve(detail(1,null,true));await p;assert.equal(await c.write('match'),false);assert.equal(writes.length,0);p=c.write('match');assert.equal(writes.length,1);assert.deepEqual(writes[0].payload,{mall_price:120});writes[0].resolve({ok:true});await new Promise(r=>setImmediate(r));reads[1].resolve({queue:[]});reads[2].resolve(detail(1,120,false));await p;const lock=c.write('lock');assert.deepEqual(writes[1].payload,{});writes[1].resolve({ok:true});await new Promise(r=>setImmediate(r));reads[3].resolve({queue:[]});reads[4].resolve(detail(1,120,true));await lock;});
test('POST in flight persists before send; reload restores uncertainty even after fresh GET',async()=>{
  let storage='[]',postCount=0;
  const old=createController({get:async()=>detail(1),post:()=>{postCount++;assert.deepEqual(JSON.parse(storage),[{code:1,phase:'writing'}]);return new Promise(()=>{});}},s=>{storage=JSON.stringify(savedBlockers(s));});
  old.permission(true);await old.select(1);void old.write('lock');
  const reloaded=createController({get:async()=>detail(1,100,true),post:async()=>{postCount++;return {ok:true};}},s=>{storage=JSON.stringify(savedBlockers(s));});
  restoreBlockers(reloaded,JSON.parse(storage));reloaded.permission(true);await reloaded.select(1);
  assert.equal(reloaded.record(1).phase,'uncertain');assert.equal(reloaded.record(1).unresolved,true);
  assert.equal(reloaded.allowed(reloaded.record(1)),false);await reloaded.write('match');await reloaded.write('lock');assert.equal(postCount,1);
  reloaded.back();await reloaded.select(1);assert.equal(reloaded.allowed(reloaded.record(1)),false);
});
test('current session success replaces writing with refresh guard then clears after fresh detail',async()=>{
  const phases=[];const c=createController({get:async url=>url.endsWith('summary')?{queue:[]}:detail(1),post:async()=>({ok:true})},s=>phases.push(savedBlockers(s).map(x=>x.phase).join(',')));
  c.permission(true);await c.select(1);await c.write('lock');assert.ok(phases.includes('writing'));assert.ok(phases.includes('refreshing'));assert.deepEqual(savedBlockers(c.state),[]);
});
test('explicit rejection clears durable writing marker but current session stays permission blocked',async()=>{
  let storage='[]';const c=createController({get:async()=>detail(1),post:async()=>{throw Object.assign(new Error('forbidden'),{status:403});}},s=>{storage=JSON.stringify(savedBlockers(s));});
  c.permission(true);await c.select(1);await c.write('lock');assert.deepEqual(JSON.parse(storage),[]);assert.equal(c.record(1).phase,'permission');assert.equal(c.allowed(c.record(1)),false);
});
