const test=require('node:test');
const assert=require('node:assert/strict');
const mod=require('../mockups/shared/admin2/sourcing-new.js');
const clone=x=>JSON.parse(JSON.stringify(x));
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const product=(code=110899)=>({product_code:code,name:'NVMe SSD',sku:'SSD-A1',stock:0,safety_stock:3,purchase:80000,state:'reply',quotes:[{quote_id:code+10,supplier_id:1,supplier:'A',price:82000,status:'회신',memo:'메모'},{quote_id:code+11,supplier_id:2,supplier:'B',price:null,status:'요청'}]});
const response=()=>({items:[product(),product(110900)],page:1,pages:2,size:50,total:70,suppliers:[{id:1,name:'A'},{id:2,name:'B'}]});
const confirm={ok:true,price:82000,purchase_before:80000,purchase_after:79000,sale_before:90000,sale_after:89000,sale_locked:false};
function fixture(extra={}){const memory={},calls=[];const storage={getItem:k=>memory[k]??null,setItem:(k,v)=>memory[k]=v};const io={storage,get:async u=>u.includes('product-meta')?{used_parts:[]}:clone(response()),post:async (u,b)=>{calls.push([u,b]);return clone(confirm);},...extra};const c=mod.createController(io);c.permission(true);return {c,io,memory,storage,calls};}
test('server page and search survive detail back; drafts remain attached across pages',async()=>{const urls=[];const f=fixture({get:async u=>{urls.push(u);const page=Number(new URL(u,'http://fixture').searchParams.get('page'));return {...response(),page,items:[product(page===2?110900:110899)]};}});await f.c.filter({q:'SSD',part:'SSD'});f.c.edit(110899,'replies',{110909:{price:'83000',memo:'초안'}});await f.c.filter({page:2});f.c.select(110900);f.c.back();assert.equal(f.c.state.query.page,2);assert.equal(f.c.state.query.q,'SSD');assert.equal(f.c.state.items[0].product_code,110900);assert.equal(f.c.draft(110899).replies[110909].price,'83000');assert.equal(f.c.can('confirm',110899),false);assert.match(urls.at(-1),/page=2/);assert.match(urls.at(-1),/part_type=SSD/);assert.equal(f.calls.length,0);});
async function ready(f){await f.c.load();f.c.select(110899);f.c.quote(110899,110909);}
test('unreplied quotes cannot be selected or confirmed; no permission or no current read blocks',async()=>{const f=fixture();await ready(f);f.c.quote(110899,110910);assert.equal(f.c.draft(110899).quote,110909);f.c.permission(false);assert.equal(await f.c.write('confirm',110899),false);f.c.permission(true);f.c.record(110899).stale=true;assert.equal(f.c.can('confirm',110899),false);assert.equal(f.calls.length,0);});
test('journal is durable before POST, duplicate is blocked, result remains on fixed product after navigation',async()=>{const pending=defer();let f;f=fixture({post:async(u,b)=>{const j=JSON.parse(f.memory[mod.JOURNAL]);assert.equal(j['sourcing:110899'].phase,'writing');f.calls.push([u,b]);return pending.promise;}});await ready(f);const writing=f.c.write('confirm',110899);f.c.select(110900);assert.equal(await f.c.write('confirm',110899),false);pending.resolve(confirm);await writing;assert.equal(f.calls.length,1);assert.equal(f.c.state.selected,110900);assert.equal(f.c.record(110899).result.data.purchase_after,79000);assert.equal(f.c.record(110900).result,null);});
test('reload during POST restores uncertainty; GET and selecting A B A never unlock it',async()=>{const pending=defer(),f=fixture({post:()=>pending.promise});await ready(f);f.c.write('confirm',110899);const restarted=mod.createController({...f.io});restarted.permission(true);await restarted.load();restarted.select(110900);restarted.select(110899);assert.equal(restarted.record(110899).unresolved,true);assert.equal(restarted.can('confirm',110899),false);assert.equal(await restarted.write('confirm',110899),false);pending.reject(Error('lost'));});
test('lost response is never automatically retried and later successful GET does not release it',async()=>{const f=fixture({post:async()=>{f.calls.push(1);throw Error('lost response');}});await ready(f);await f.c.write('confirm',110899);await f.c.load();assert.equal(f.c.record(110899).phase,'uncertain');assert.equal(await f.c.write('confirm',110899),false);assert.equal(f.calls.length,1);});
test('known successful POST followed by GET failure preserves response and blocks writes until fresh exact row',async()=>{let fail=false;const f=fixture({get:async()=>{if(fail)throw Error('read failure');return clone(response());},post:async()=>{fail=true;return confirm;}});await ready(f);await f.c.write('confirm',110899);assert.equal(f.c.record(110899).phase,'refresh_failed');assert.equal(f.c.record(110899).result.data.price,82000);assert.equal(f.c.can('confirm',110899),false);fail=false;await f.c.load();assert.equal(f.c.record(110899).phase,'ready');});
test('old list response after search cannot overwrite newest list or query',async()=>{const slow=defer(),fast=defer();let n=0;const f=fixture({get:()=>++n===1?slow.promise:fast.promise});const first=f.c.load();const second=f.c.filter({q:'new',page:2});fast.resolve({...response(),page:2,items:[product(110900)]});await second;slow.resolve(response());await first;assert.equal(f.c.state.items[0].product_code,110900);assert.equal(f.c.state.query.page,2);assert.equal(f.c.state.query.q,'new');});
test('request and reply preserve draft and send unique selected supplier IDs and fixed reply payload',async()=>{let data=response();data.items[0].quotes=[];const f=fixture({get:async()=>clone(data),post:async(u,b)=>{f.calls.push([u,b]);return u.endsWith('/request')?{ok:true,batch_id:5,quotes:[]}:{ok:true,price:b.price};}});await f.c.load();f.c.edit(110899,'suppliers',[1,1,2]);await f.c.write('request',110899);assert.deepEqual(f.calls[0][1],{product_code:110899,supplier_ids:[1,2]});data=response();await f.c.load();f.c.edit(110899,'replies',{110910:{price:'85000',memo:'대행 회신'}});await f.c.write('reply',110899,110910);assert.deepEqual(f.calls[1],[ '/api/admin/sourcing/quotes/110910/reply',{price:85000,memo:'대행 회신'}]);f.c.select(110900);f.c.back();assert.equal(f.c.draft(110899).replies[110910].memo,'대행 회신');});
test('unavailable or corrupted journal blocks POST before it is sent',async()=>{for(const storage of [{getItem:()=>'{broken',setItem:()=>{}},{getItem:()=>null,setItem:()=>{throw Error('quota');}}]){const f=fixture({storage});await ready(f);assert.equal(await f.c.write('confirm',110899),false);assert.equal(f.calls.length,0);}});
test('403 permission and 409 conflict remain blocked and require fresh explicit review',async()=>{const f=fixture({post:async()=>{const e=Error('변경됨');e.status=409;throw e;}});await ready(f);await f.c.write('confirm',110899);assert.equal(f.c.record(110899).phase,'conflict');await f.c.load();assert.equal(f.c.can('confirm',110899),false);f.c.acceptRead(110899);assert.equal(f.c.can('confirm',110899),true);f.io.post=async()=>{const e=Error('권한');e.status=403;throw e;};await f.c.write('confirm',110899);assert.equal(f.c.can('confirm',110899),false);});

test('validated stock acknowledgement in shared journal remains valid on sourcing page',async()=>{const journal={'stock:110899':{mode:'stock',code:110899,phase:'saved',action:'inbound',result:{action:'inbound',data:{ok:true,undo_id:9,stock_before:0,stock_after:5,pool_entered:false}}}};const f=fixture({storage:{getItem:()=>JSON.stringify(journal),setItem:()=>{}}});await ready(f);assert.equal(f.c.state.journalError,false);assert.equal(f.c.can('confirm',110899),true);});
