const test=require('node:test');const assert=require('node:assert/strict');const mod=require('../mockups/shared/admin2/stock-inbound-new.js');
const clone=x=>JSON.parse(JSON.stringify(x));const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const p=(code=110899)=>({product_code:code,name:'NVMe SSD',sku:'SSD-A1',stock:0,safety_stock:3,purchase:80000,status:'품절',why:'inbound',hold:null,pool_label:'입고 후 판정'});
const list=()=>({items:[p(),p(110900)],catalog:[],page:1,pages:1,size:50,total:2,kind_counts:{all:2,zero:2,low:0},held_total:0});
const hist=(code=null)=>({items:[{log_id:77,product_code:code??110901,undoable:true,stock_now:6,kind:'inbound'}],product_code:code,page:1,pages:1,size:20,total:1,can_write:true});
const success={ok:true,undo_id:9,stock_before:0,stock_after:5,status_changed:true,pool_entered:false};
function fixture(extra={}){const memory={},calls=[];const storage={getItem:k=>memory[k]??null,setItem:(k,v)=>memory[k]=v};const io={storage,get:async u=>u.includes('/history')?hist(u.includes('product_code=')?Number(u.split('product_code=')[1]):null):clone(list()),post:async(u,b)=>{calls.push([u,b]);return clone(success);},...extra};const c=mod.createController(io);c.permission(true);return {c,io,storage,memory,calls};}
async function ready(f){await f.c.load();f.c.edit(110899,'qty','5');}
test('server list and history pages are preserved without losing drafts or enabling missing row writes',async()=>{const urls=[];const f=fixture({get:async u=>{urls.push(u);const params=new URL(u,'http://fixture').searchParams,page=Number(params.get('page'));if(u.includes('/history'))return {...hist(params.has('product_code')?Number(params.get('product_code')):null),page,pages:2,total:21};return {...list(),page,pages:2,total:51,items:page===2?[p(110901)]:list().items};}});await ready(f);await f.c.filter({page:2});f.c.select(110901);f.c.back();assert.equal(f.c.state.query.page,2);assert.equal(f.c.draft(110899).qty,'5');assert.equal(f.c.can('inbound',110899),false);await f.c.history(110901,2);assert.equal(f.c.state.history.page,2);assert.match(urls.at(-1),/history\?page=2/);await f.c.filter({page:1});assert.equal(f.c.can('inbound',110899),true);assert.equal(f.calls.length,0);});
test('empty, zero, negative, decimal, exponent and unsafe quantities block real action; permission and hold block',async()=>{const f=fixture();await ready(f);for(const qty of ['',0,-1,'1.5','1e2','9007199254740993']){f.c.edit(110899,'qty',qty);assert.equal(f.c.can('inbound',110899),false);}f.c.edit(110899,'qty','5');f.c.edit(110899,'why','adjust');assert.equal(f.c.can('inbound',110899),true);f.c.record(110899).item.hold={reason:'보류'};assert.equal(f.c.can('inbound',110899),false);f.c.record(110899).item.hold=null;f.c.permission(false);assert.equal(await f.c.write('inbound',110899),false);assert.equal(f.calls.length,0);});
test('single per-product draft survives details, back and query changes',async()=>{const f=fixture();await ready(f);f.c.select(110899);f.c.select(110900);f.c.back();await f.c.filter({kind:'low'});assert.equal(f.c.draft(110899).qty,'5');assert.equal(f.c.draft(110900).qty,'');});
test('fixed product and payload, durable journal, and duplicate protection during asynchronous write',async()=>{const d=defer();let f;f=fixture({post:(u,b)=>{assert.equal(JSON.parse(f.memory[mod.JOURNAL])['stock:110899'].phase,'writing');f.calls.push([u,b]);return d.promise;}});await ready(f);const writing=f.c.write('inbound',110899);f.c.select(110900);f.c.edit(110899,'qty','9');assert.equal(await f.c.write('inbound',110899),false);d.resolve(success);await writing;assert.deepEqual(f.calls[0],['/api/admin/stock-inbound/110899',{qty:5,why:'inbound'}]);assert.equal(f.c.record(110899).result.data.stock_after,5);assert.equal(f.c.record(110900).result,null);});
test('reload before response and network failure stay uncertain through GET; no automatic POST retry',async()=>{const d=defer(),f=fixture({post:(u,b)=>{f.calls.push([u,b]);return d.promise;}});await ready(f);const pending=f.c.write('inbound',110899);const restarted=mod.createController({...f.io});restarted.permission(true);await restarted.load();restarted.edit(110899,'qty','5');assert.equal(restarted.can('inbound',110899),false);d.reject(Error('lost'));await pending;await f.c.load();assert.equal(f.c.record(110899).phase,'uncertain');assert.equal(await f.c.write('inbound',110899),false);assert.equal(f.calls.length,1);});
test('known success but row missing after reload is not guessed from an unrelated list item',async()=>{let saved=false;const f=fixture({post:async()=>{saved=true;return success;},get:async u=>u.includes('/history')?hist():{...list(),items:saved?[p(110900)]:list().items}});await ready(f);await f.c.write('inbound',110899);assert.equal(f.c.record(110899).phase,'refresh_failed');assert.equal(f.c.record(110899).stale,true);assert.equal(f.c.can('inbound',110899),false);assert.equal(f.c.record(110899).result.data.stock_after,5);});
test('past inbound undo uses fresh server history outside pending list and attaches result to that product only',async()=>{const f=fixture({post:async(u,b)=>{f.calls.push([u,b]);return {ok:true,stock_after:2,sku:'OLD'};}});await ready(f);await f.c.history(null,1);f.c.select(110899);await f.c.history(null,1);assert.equal(f.c.can('undo',110901,77),true);await f.c.write('undo',110901,77);assert.equal(f.calls[0][0],'/api/admin/stock-inbound/undo/77');assert.equal(f.c.record(110899).result,null);assert.equal(f.c.record(110901).result.action,'undo');});
test('stale history response after A B A cannot change selected product history',async()=>{const d=defer();let n=0;const f=fixture({get:u=>u.includes('/history')?(++n===1?d.promise:Promise.resolve(hist(110900))):Promise.resolve(list())});await ready(f);const first=f.c.history(110899,1);await f.c.history(110900,1);d.resolve(hist(110899));await first;assert.equal(f.c.state.history.product_code,110900);});
test('hold and release preserve fixed product, whitespace reason is rejected, no new policy',async()=>{const f=fixture({post:async(u,b)=>{f.calls.push([u,b]);return {ok:true,hold_id:3,reason:'지연'};}});await ready(f);f.c.edit(110899,'holdReason','   ');assert.equal(f.c.can('hold',110899),false);f.c.edit(110899,'holdReason',' 납기 지연 ');await f.c.write('hold',110899);assert.deepEqual(f.calls[0],['/api/admin/stock-inbound/hold/110899',{reason:'납기 지연'}]);f.c.record(110899).item.hold={hold_id:3};await f.c.write('release',110899);assert.equal(f.calls[1][0],'/api/admin/stock-inbound/hold/110899/release');});
test('catalog request uses existing name/SKU search and hides no invented exact GET route',async()=>{const urls=[];const f=fixture({get:async u=>{urls.push(u);return {...list(),catalog:[p()]};}});await f.c.filter({mode:'catalog',q:'SSD-A1'});assert.match(urls[0],/catalog_q=SSD-A1/);assert.equal(f.c.state.items.length,1);assert.equal(f.c.can('hold',110899),false);});
test('unknown JSON success and corrupt storage both prevent further mutation',async()=>{const f=fixture({post:async()=>({ok:true})});await ready(f);await f.c.write('inbound',110899);assert.equal(f.c.record(110899).unresolved,true);const bad=fixture({storage:{getItem:()=>'{"bad":null}',setItem:()=>{}}});await ready(bad);assert.equal(await bad.c.write('inbound',110899),false);assert.equal(bad.calls.length,0);});

test('history GET begun before POST cannot overwrite history after the write boundary',async()=>{const d=defer();let reads=0;const f=fixture({get:u=>u.includes('/history')?(++reads===1?d.promise:Promise.resolve(hist(110900))):Promise.resolve(list())});await ready(f);const old=f.c.history(110900,1);await f.c.write('inbound',110899);d.resolve({...hist(110900),can_write:false});await old;assert.equal(f.c.state.history.product_code,110900);assert.equal(f.c.state.canWrite,true);assert.equal(f.c.state.history.can_write,true);});

test('filtered history containing a different product is rejected and never enables undo',async()=>{const f=fixture({get:async u=>u.includes('/history')?{...hist(110899),items:hist().items}:list()});await ready(f);await f.c.history(110899,1);assert.match(f.c.state.historyError,/응답 형식/);assert.equal(f.c.can('undo',110901,77),false);});
test('same-tab unresolved sourcing journal blocks stock writes for that product',async()=>{const f=fixture();f.storage.setItem(mod.JOURNAL,JSON.stringify({'sourcing:110899':{mode:'sourcing',code:110899,phase:'uncertain'}}));await ready(f);assert.equal(f.c.journalBlocked(110899),true);assert.equal(await f.c.write('inbound',110899),false);assert.equal(f.calls.length,0);});

test('saved journal missing its validated acknowledgement is corrupt and never unlocks via GET',async()=>{const memory=JSON.stringify({'stock:110899':{mode:'stock',code:110899,phase:'saved',action:'inbound'}});const f=fixture({storage:{getItem:()=>memory,setItem:()=>{}}});await ready(f);assert.equal(f.c.state.journalError,true);assert.equal(await f.c.write('inbound',110899),false);assert.equal(f.calls.length,0);});
