"""Preserve generated bytes across deployment until cloud storage succeeds."""
from alembic import op
revision='0121'
down_revision='0120'
branch_labels=None
depends_on=None
def upgrade():
    op.execute('ALTER TABLE pc_media_jobs ADD COLUMN staged_png BYTEA')
def downgrade():
    op.execute('ALTER TABLE pc_media_jobs DROP COLUMN staged_png')
