(function(){'use strict';
const F=window.MVP3Fixtures,M=window.MVP3Model,A=window.MVP3Api;
const $=s=>document.querySelector(s), view=$('#view'), actions=$('#actions'), dlg=$('#gpu-dialog');
const STORAGE='popcorn-mvp3-demo-quote-v1';
const state={screen:'welcome',applied:M.selection(),draft:M.selection(),selected:'A',budget:F.budget,resolution:'FHD',messages:[],query:'',sort:'recommended',compatible:true,saved:false};
let trigger=null,timer;
const mobile=matchMedia('(max-width:760px)');
let chatPreference=null;
function syncChat(){
  const open=!mobile.matches||(chatPreference??state.screen==='welcome');
  const body=$('#chat-body'),toggle=$('#chat-toggle');
  if(!open&&body.contains(document.activeElement))toggle.focus({preventScroll:true});
  body.hidden=!open;toggle.setAttribute('aria-expanded',String(open));
  $('#chat-toggle-label').textContent=open?'상담 접기 ▴':'상담 내용 보기 ▾';
  $('#chat-summary').textContent=state.screen==='welcome'?'게임과 예산을 알려주세요':`배그·롤 / 예산 ${state.budget/10000}만원 · ${state.resolution} · 본체만 임시 기준`;
}
mobile.addEventListener('change',syncChat);
$('#chat-toggle').addEventListener('click',()=>{chatPreference=$('#chat-toggle').getAttribute('aria-expanded')!=='true';syncChat();});
function changeSummary(q){
  const base=M.quote(M.selection()),delta=q.total-base.total,more=q.ssd.id==='2TB';
  const title=delta===0?(more?'추가금액 없이 저장공간을 늘렸어요':'총 금액은 기존 견적과 같아요'):delta>0?`${money(delta)} 추가되는 변경안이에요`:`${money(-delta)} 줄어드는 변경안이에요`;
  const performance=q.gpu.pubg<base.gpu.pubg?'게임 성능은 조금 낮아지고':q.gpu.pubg>base.gpu.pubg?'게임 성능은 높아지고':'게임 성능은 같고';
  return `<section class="change-summary" aria-label="변경 효과 요약"><h3>${title}</h3><p>${performance}, ${more?'SSD 용량은 2배가 돼요':'SSD는 기존 1TB를 유지해요'}.</p></section>`;
}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${v.toLocaleString('ko-KR')}원`,signed=v=>`${v>0?'+':v<0?'−':''}${money(Math.abs(v))}`;
const icon=(name,cls='')=>`<img class="icon ${cls}" src="../shared/icons/su/${name}.svg" alt="">`;
function button(label,action,cls='',data=''){return `<button type="button" class="${cls}" data-action="${action}" ${data}>${label}</button>`;}
function notice(text){$('#notice').textContent=text;$('#notice').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#notice').hidden=true,6000);}
function say(text,who='ai'){state.messages.push({text,who});renderMessages();}
function renderMessages(){const el=$('#messages');el.innerHTML=state.messages.map(x=>`<div class="message ${x.who==='user'?'user':'ai'}"><span class="avatar">${x.who==='user'?icon('ms-person'):'AI'}</span><p>${esc(x.text)}</p></div>`).join('');el.scrollTop=el.scrollHeight;$('#suggestions').innerHTML=(state.screen==='welcome'?['배그와 롤, 150만원으로 추천해줘','아직 잘 모르겠어요']:['저장공간을 2TB로 바꿔줘','다른 GPU를 고르고 싶어']).map(x=>button(esc(x),'prompt','chip',`data-text="${esc(x)}"`)).join('');}
function budget(total){const gap=state.budget-total;return gap>0?`예산보다 ${money(gap)} 낮아요`:gap<0?`예산보다 ${money(-gap)} 높아요`:'예산과 같아요';}
function badge(){return `<span class="data-note">이미지·가격·성능·호환성은 가상 예시예요.</span>`;}
function chips(){return `<div class="requirements">${button(`${icon('ms-sports_esports')} 배그 · 롤`,'conditions','chip')}${button(`예산 ${(state.budget/10000).toLocaleString('ko-KR')}만원`,'conditions','chip')}${button(`${state.resolution} · ${state.resolution==='FHD'?'임시 기준':'선택 조건'}`,'conditions','chip assumed')}${button('본체만 · 임시 기준','conditions','chip assumed')}</div>`;}
function heading(title,back){return `${back?button('← 이전 화면','back','back'):''}<div class="title-row"><h2 tabindex="-1">${title}</h2>${badge()}</div>${chips()}`;}
function summary(s){const q=M.quote(s);return `<section class="summary"><div><h3>${s.gpu==='A'?'메모리와 저장공간을 넉넉하게':`GPU ${s.gpu} · 저장공간 ${s.ssd} 구성`}</h3><p>32GB 메모리와 ${s.ssd} SSD를 담은 예시 본체 구성이에요.</p></div><div><strong class="price">${money(q.total)}</strong><p class="${q.total>state.budget?'warn-text':'green'}">${budget(q.total)}</p></div></section>`;}
function productImage(kind){return `<img class="product-image" src="assets/${kind}.png" alt="${kind==='gpu'?'가상 그래픽카드 제품 이미지':kind==='ssd'?'가상 SSD 제품 이미지':'가상 PC 본체 이미지'}">`;}
function specs(part,q){if(part.key==='gpu')return [['제품명',q.gpu.name+' (예시)'],['그래픽 메모리',q.gpu.id==='B'?'12GB GDDR6':'8GB GDDR6'],['냉각 방식','듀얼팬'],['제품 길이',`${q.gpu.length}mm (예시)`],['화면 연결','HDMI · DisplayPort']];if(part.key==='ssd')return [['저장 용량',q.ssd.id],['인터페이스','NVMe · M.2'],['순차 읽기 속도','5,000 MB/s (예시)'],['게임 설치 여유',`약 ${q.ssd.games}개 (단순 예시)`]];return part.specs;}
function parts(s){const q=M.quote(s);return `<div class="section-title"><h3>부품 구성과 선택 이유</h3>${button('모든 상세 사양 펼치기','expand-all','text-button')}</div><div class="parts">${F.parts.map(p=>{const item=p.key==='gpu'?q.gpu:p.key==='ssd'?q.ssd:p;const changed=(p.key==='gpu'&&s.gpu!=='A')||(p.key==='ssd'&&s.ssd!=='1TB');return `<article class="part" data-part="${p.key}"><div class="part-line">${icon(p.icon)}<div><h4>${p.label} <span>${esc(item.name)}</span>${changed?'<em>변경</em>':''}</h4><p>${p.description}</p></div><strong>${money(item.price)}</strong>${['gpu','ssd'].includes(p.key)?button('변경',p.key==='gpu'?'gpu':'ssd','outline small'):''}</div><details><summary>상세 사양 <span class="when-closed">펼치기</span><span class="when-open">접기</span></summary><div class="part-expanded">${p.key==='gpu'?productImage('gpu'):icon(p.icon,'large-icon')}<div><h4>${p.label} 상세 정보</h4><dl>${specs(p,q).map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></div><div><h4>어떤 역할을 하나요?</h4><p>${p.description}</p><h4>선택할 때 확인하세요</h4><p>${p.reason}</p>${button(`이 부품에 대해 질문하기`,'ask','text-button',`data-part="${p.key}"`)}</div></div></details></article>`;}).join('')}</div>`;}
function footer(total,primary,action,secondary,secondaryAction){actions.innerHTML=`<div><span>총 견적 · 가상 예시</span><strong>${money(total)}</strong></div><div class="footer-buttons">${secondary?button(secondary,secondaryAction,'outline'):''}${button(primary,action,'primary')}</div>`;actions.hidden=false;}
function render(focus=true){
  view.dataset.screen=state.screen;
  if(state.screen==='welcome'){view.innerHTML=`<div class="title-row"><h2>나에게 맞는 PC</h2>${badge()}</div><p>말씀해주신 조건에 맞춰 이곳에 견적을 정리해드려요.</p><section class="empty"><img src="../shared/icons/su/ms-desktop_windows.svg" alt=""><h3>어떤 PC가 필요한지 들려주세요</h3><p>게임과 예산만 알려주셔도 시작할 수 있어요.</p><div class="steps"><span>01 조건 말하기</span><span>02 견적 비교하기</span><span>03 부품 확인하기</span></div>${button('배그·롤 150만원 예시 시작','start','primary')}</section>`;actions.hidden=true;
  }else if(state.screen==='results'){view.innerHTML=heading('나에게 맞는 PC')+`<p>예산과 사용 조건을 비교할 수 있는 두 가지 예시입니다.</p><div class="quote-cards"><section class="quote-card"><span class="pill">알뜰 구성</span>${productImage('pc')}<h3>예산 여유를 남기는 구성</h3><p>메모리 16GB · SSD 500GB의 간단한 비교 예시예요.</p><strong class="price">1,290,000원</strong><p>실제 판매 구성으로 연결되지 않았어요.</p>${button('알뜰 구성 안내','economy','outline')}</section><section class="quote-card"><span class="pill strong">추천 구성</span>${productImage('pc')}<h3>메모리와 저장공간을 넉넉하게</h3><p>32GB 메모리와 1TB 저장공간을 담았어요.</p><strong class="price">1,490,000원</strong><p>${budget(F.baseTotal)}</p>${button('추천 견적 자세히 보기','detail','primary')}</section></div><p class="muted">해상도·포함 품목은 임시 기준이며 구매 전 확인이 필요해요.</p>`;actions.hidden=true;
  }else if(state.screen==='detail'){view.innerHTML=heading('추천 구성 상세',true)+summary(state.applied)+parts(state.applied);footer(M.quote(state.applied).total,'이 견적으로 확인','final','구성 변경 요청','gpu');
  }else if(state.screen==='compare'){renderCompare();
  }else if(state.screen==='final'){renderFinal();}
  renderMessages();syncChat();if(focus){view.scrollTop=0;view.querySelector('h2')?.focus({preventScroll:true});if(mobile.matches)window.scrollTo(0,0);}updateHistory();
}
function comparisonTable(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>i===0?`<th scope="row">${x}</th>`:`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function renderCompare(){
 const q=M.quote(state.draft),base=M.quote(M.selection()),gpuChanged=q.gpu.id!=='A',ssdChanged=q.ssd.id!=='1TB';
 const card=(kind,label,name,price,delta)=>`<div class="product-compare-card">${productImage(kind)}<div class="product-copy"><p>${label}</p><h4>${name}</h4><div class="product-price"><strong>${money(price)}</strong>${delta==null?'':`<span class="delta">${signed(delta)}</span>`}</div></div></div>`;
 const beforeAfter=(kind,a,b)=>`<div class="before-after">${a}<span class="arrow" aria-hidden="true">→</span>${b}</div>`;
 view.innerHTML=heading('변경안 함께 확인',true)+`<div class="compare-status"><span class="pill">미저장 · ${Number(gpuChanged)+Number(ssdChanged)}개 변경</span>${button('조건 수정','conditions','text-button mobile-conditions')}</div>`+changeSummary(q)+
 (gpuChanged?`<section class="change-section gpu-change"><div class="section-title"><h3>1. 그래픽카드<span class="gpu-label"> (GPU)</span></h3><div class="section-controls">${button('다른 GPU 선택','gpu','text-button')}</div></div><div class="product-context">${productImage('gpu')}<p>게임의 프레임을 결정하는 핵심 부품이에요.</p></div>${beforeAfter('gpu',card('gpu','기존 견적 GPU',base.gpu.name,base.gpu.price,null),card('gpu','변경안 GPU',q.gpu.name,q.gpu.price,q.gpuDelta))}<h4 class="performance-title">게임 성능과 호환성 비교</h4><p class="muted performance-note">FHD · 높음 설정 · 동일 CPU · 평균 FPS 가상 예시</p>${comparisonTable(['항목','기존 GPU','변경 GPU'],[['배틀그라운드',`${base.gpu.pubg} FPS`,`${q.gpu.pubg} FPS`],['리그 오브 레전드',`${base.gpu.lol} FPS`,`${q.gpu.lol} FPS`]])}<div class="gpu-secondary">${button('GPU 변경 취소','cancel-gpu','text-button')}</div><details class="compatibility-details"><summary>호환성 상세 확인 · 실조립 확인 전</summary><dl class="checks"><div><dt>파워 · 전원 단자</dt><dd>권장 ${q.gpu.power}W · 구성 650W · 8핀 1개 (가상 예시)</dd></div><div><dt>케이스 장착 길이</dt><dd>GPU ${q.gpu.length}mm · 케이스 330mm · ${330-q.gpu.length}mm 여유 (가상 예시)</dd></div><div><dt>호환성</dt><dd>문서상 조건 충족 예시 · 실조립 확인 전</dd></div></dl></details></section>`:'')+
 (ssdChanged?`<section class="change-section ssd-change"><div class="section-title"><h3>2. 함께 변경할 저장장치</h3>${button('SSD 변경 취소','cancel-ssd','text-button')}</div><div class="product-context">${productImage('ssd')}<p>더 넓은 저장공간으로 게임과 프로그램을 여유롭게 설치할 수 있어요.</p></div>${beforeAfter('ssd',card('ssd','기존 견적 SSD','SSD 1TB',base.ssd.price,null),card('ssd','변경안 SSD','SSD 2TB',q.ssd.price,q.ssdDelta))}<p class="tint storage-benefit">게임을 지우고 다시 설치하는 번거로움이 줄어요.</p><h4>저장공간과 사용 경험 비교</h4>${comparisonTable(['항목','기존 SSD','변경 SSD'],[['저장 용량','1TB','2TB'],['게임 설치 여유','약 8개','약 18개'],['순차 읽기 속도','5,000 MB/s','5,000 MB/s'],['게임 로딩','비슷한 수준','비슷한 수준']])}<p class="muted">게임당 100GB, 시스템·여유 공간 200GB를 제외한 단순 예시예요. 설치 공간은 늘고 속도는 비슷해요.</p></section>`:'<p class="muted">저장장치는 기존 1TB를 유지해요.</p>')+
 `<section class="totals"><p>기존 견적 ${money(base.total)} → 변경안 <strong>${money(q.total)}</strong></p><p>GPU ${signed(q.gpuDelta)} · SSD ${signed(q.ssdDelta)} · 추가 ${signed(q.total-base.total)}</p><p class="${q.total>state.budget?'warning':'tint'}">${budget(q.total)}</p><p class="muted">가격 실제 확인 전 · 재고 미확인 · 판매조건 재확인 필요</p></section>`;
 footer(q.total,'이 구성으로 견적 확인','apply-draft','기존 구성 유지','keep');
}
function salesConditions(){const c=A.conditions(F.conditions),labels={os:'운영체제',keyboard:'키보드',mouse:'마우스',monitor:'모니터',warranty:'보증'};return `<section class="sales"><h3>구매 전 확인할 내용</h3><dl class="checks"><div><dt>호환성</dt><dd>문서상 조건 충족 예시 · 실조립 검수 전</dd></div><div><dt>가격 / 재고</dt><dd>예시 금액 · 실제 가격 확인 전 / 재고 미확인</dd></div>${Object.entries(c).map(([key,v])=>`<div><dt>${labels[key]}</dt><dd><span class="pill">${v.needs_reconfirmation?'재확인 필요':'미확인'}</span> ${esc(v.customer_statement)}</dd></div>`).join('')}</dl><p class="muted">구성 변경 후 판매조건을 다시 확인해야 해요. 확인 전에는 포함 여부를 단정하지 않아요.</p></section>`;}
function renderFinal(){const q=M.quote(state.applied);view.innerHTML=heading('최종 견적 확인',true)+`<span class="pill ${state.saved?'strong':''}">${state.saved?'데모 저장됨':'아직 저장 전'}</span>`+summary(state.applied)+(q.gpu.id!=='A'||q.ssd.id!=='1TB'?changeSummary(q):'')+parts(state.applied)+salesConditions()+`<p class="muted">데모 저장은 구성 보관이며, 주문·결제·재고 확보가 아닙니다.</p>`;footer(q.total,state.saved?'데모 견적 다시 저장':'데모 견적 저장하기','save','구성 다시 수정','edit');}
function start(text){state.screen='results';state.applied=M.selection();state.draft=M.selection();state.saved=false;say(text||'배그랑 롤 하고, 예산은 150만원 정도예요','user');say('게임과 예산을 확인했어요. 우선 FHD·본체만 기준의 예시 견적을 보여드릴게요.');render();}
function request(text){if(!text.trim()){notice('원하는 조건을 입력해주세요.');$('#request').focus();return;}if(state.screen==='welcome'){if(/모르/.test(text)){say(text,'user');say('즐기는 게임이나 사용 목적 한 가지만 먼저 알려주세요. 배그·롤 예시로도 시작할 수 있어요.');return;}if(!/배그|롤|게임|150/.test(text)){say(text,'user');say('현재 데모는 배그·롤 150만원 예시를 지원해요. 이 예시로 흐름을 확인해주세요.');return;}start(text);return;}say(text,'user');if(/2\s*TB|2테라/i.test(text)){state.draft=M.change(state.draft,'ssd','2TB');state.screen='compare';state.saved=false;say('SSD 2TB 변경안을 추가했어요. 70,000원이 늘고, 다른 부품 변경안은 유지돼요.');render();}else if(/GPU|그래픽/i.test(text)){say('GPU 후보를 비교해서 골라보세요. SSD 변경안은 유지할게요.');openGpu();}else if(/예산|150/.test(text)){state.draft=M.change(state.draft,'gpu','C');state.screen='compare';say('가상 후보 C를 비교해보세요. 성능은 소폭 낮지만 SSD 변경과 함께 예산을 맞출 수 있어요.');render();}else{say('이 데모에서는 GPU 후보 선택과 SSD 1TB·2TB 변경을 확인할 수 있어요. 실제 상담 연결은 준비 중입니다.');}}
function updateHistory(){const hash='#'+state.screen;if(location.hash!==hash)history.pushState({screen:state.screen},'',hash);}
function back(){const map={results:'welcome',detail:'results',compare:'detail',final:'compare'};state.screen=map[state.screen]||'welcome';render();}
function openGpu(){trigger=document.activeElement;state.selected=state.draft.gpu;state.query='';state.sort='recommended';renderGpu();dlg.showModal();dlg.querySelector('button')?.focus();}
function renderGpu(){let list=F.gpus.filter(x=>(!state.compatible||x.compatible)&&x.name.toLowerCase().includes(state.query.toLowerCase()));if(state.sort==='price')list=[...list].sort((a,b)=>a.price-b.price);dlg.innerHTML=`<div class="drawer-head"><div><h2 id="gpu-title">다른 GPU 선택</h2><p>가격과 게임 성능을 비교해 변경할 제품을 골라주세요.</p></div>${button('×','close-gpu','close','aria-label="GPU 선택 닫기"')}</div>${badge()}<p class="tint">SSD ${state.draft.ssd} 변경안 유지 · ${signed(M.quote(state.draft).ssdDelta)} 포함</p><div class="filters"><label><span class="sr-only">GPU 검색</span><input id="gpu-search" type="search" value="${esc(state.query)}" placeholder="제품명으로 찾기"></label><label><input id="compatible" type="checkbox" ${state.compatible?'checked':''}> 호환되는 예시 제품만</label><label><span class="sr-only">GPU 정렬</span><select id="gpu-sort"><option value="recommended" ${state.sort==='recommended'?'selected':''}>추천순</option><option value="price" ${state.sort==='price'?'selected':''}>가격 낮은 순</option></select></label></div>${list.length?`<div class="candidate-scroll"><table class="candidate-table"><thead><tr><th>제품 선택</th>${list.map(g=>`<th class="${state.selected===g.id?'selected':''}"><label class="candidate"><input type="radio" name="gpu-candidate" value="${g.id}" ${state.selected===g.id?'checked':''}><span>${g.id==='A'?'기존 견적':g.id==='B'?'성능 여유':'가격 절약'}</span>${productImage('gpu')}<strong>${g.name}</strong><b>${money(g.price)}</b></label></th>`).join('')}</tr></thead><tbody>${[['기존 견적 대비',g=>signed(g.price-500000)],['배틀그라운드',g=>g.pubg+' FPS'],['리그 오브 레전드',g=>g.lol+' FPS'],['권장 파워',g=>g.power+'W'],['제품 길이',g=>g.length+'mm'],['호환성',()=> '장착 가능 (가상 예시)'],['선택 시 전체 견적',g=>`<strong>${money(M.quote(M.change(state.draft,'gpu',g.id)).total)}</strong><small>${budget(M.quote(M.change(state.draft,'gpu',g.id)).total)}</small>`]].map(([name,fn])=>`<tr><th scope="row">${name}</th>${list.map(g=>`<td class="${state.selected===g.id?'selected':''}">${fn(g)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="empty small-empty"><h3>검색 결과가 없어요</h3><p>A, B, C 예시 제품명으로 검색해주세요.</p></div>'}<p class="tint">C는 기존 A보다 성능이 조금 낮고 가격은 70,000원 낮은 가상 후보예요. 예산 충족 여부는 전체 견적을 확인해주세요.</p><div class="drawer-footer"><div>선택 제품 <strong>그래픽카드 ${state.selected}</strong><span>변경 예상 ${money(M.quote(M.change(state.draft,'gpu',state.selected)).total)}</span></div>${button('취소','close-gpu','outline')}${button('이 GPU로 변경안 갱신','choose-gpu','primary',list.some(g=>g.id===state.selected)?'':'disabled')}</div><p class="muted">아직 저장되지 않았어요. 다음 화면에서 두 변경을 함께 확인해요.</p>`;}
function closeGpu(){dlg.close();trigger?.focus();}
function openConditions(){trigger=document.activeElement;const d=$('#conditions-dialog');d.innerHTML=`<h2 id="conditions-title">상담 조건 수정</h2><p>실제 추천을 다시 조회하지 않는 로컬 데모예요.</p><form id="conditions-form"><label>예산 (만원)<input name="budget" type="number" min="70" max="300" value="${state.budget/10000}" required></label><label>해상도<select name="resolution"><option ${state.resolution==='FHD'?'selected':''}>FHD</option><option ${state.resolution==='QHD'?'selected':''}>QHD</option></select></label><p>성능 표는 FHD 기준의 가상 예시를 유지해요. QHD 성능은 확인 전입니다.</p><button type="submit" class="primary">조건 반영</button>${button('취소','close-conditions','outline')}</form>`;d.showModal();d.querySelector('input').focus();}
function save(){const payload=M.savedPayload(state.applied);try{localStorage.setItem(STORAGE,JSON.stringify(payload));state.saved=true;render(false);notice('이 브라우저에 예시 구성만 저장했어요. 실제 견적 저장이나 주문은 진행되지 않았어요.');}catch{state.saved=false;notice('브라우저 저장 공간을 사용할 수 없어요. 구성은 현재 화면에 유지됩니다.');}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;switch(a){case'new':chatPreference=null;$('#request').value='';state.screen='welcome';state.applied=M.selection();state.draft=M.selection();state.saved=false;state.messages=[];say('안녕하세요! 즐기는 게임과 예산을 알려주시면 나에게 맞는 PC를 함께 찾아드릴게요.');render();break;case'saved':try{const raw=localStorage.getItem(STORAGE);if(!raw){notice('저장된 데모 견적이 없어요.');break;}state.applied=M.loadSaved(raw);state.draft={...state.applied};state.screen='final';state.saved=true;render();}catch{notice('저장된 데모 견적을 읽을 수 없어요. 새 상담으로 다시 시작해주세요.');}break;case'prompt':request(b.dataset.text);break;case'start':start();break;case'economy':notice('알뜰 구성은 비교용 안내입니다. 부품 변경 흐름은 추천 구성에서 확인해주세요.');break;case'detail':state.screen='detail';render();break;case'back':back();break;case'expand-all':{const ds=[...view.querySelectorAll('details')],open=ds.some(x=>!x.open);ds.forEach(x=>x.open=open);b.textContent=open?'모든 상세 사양 접기':'모든 상세 사양 펼치기';break;}case'ask':{const p=F.parts.find(x=>x.key===b.dataset.part);say(`${p.label}를 설명해줘`,'user');say(p.description+' '+p.reason);chatPreference=true;syncChat();if(mobile.matches){$('#chat-toggle').scrollIntoView({block:'start'});$('#request').focus({preventScroll:true});}break;}case'gpu':openGpu();break;case'ssd':state.draft=M.change(state.draft,'ssd',state.draft.ssd==='1TB'?'2TB':'1TB');state.screen='compare';state.saved=false;say('저장장치 변경안을 갱신했어요. GPU 변경안은 그대로 유지해요.');render();break;case'cancel-gpu':state.draft=M.change(state.draft,'gpu','A');render();break;case'cancel-ssd':state.draft=M.change(state.draft,'ssd','1TB');render();break;case'keep':state.draft={...state.applied};state.screen='detail';render();break;case'close-gpu':closeGpu();break;case'choose-gpu':state.draft=M.change(state.draft,'gpu',state.selected);state.screen='compare';state.saved=false;closeGpu();say('GPU 변경안과 SSD 변경안을 함께 정리했어요. 아직 저장하지 않았습니다.');render();break;case'apply-draft':state.applied={...state.draft};state.screen='final';state.saved=false;say('선택한 구성을 견적에 반영했어요. 판매조건과 확인 항목을 살펴본 뒤 데모 견적을 저장해주세요.');render();break;case'final':state.screen='final';render();break;case'edit':state.screen='detail';state.draft={...state.applied};render();break;case'save':save();break;case'conditions':openConditions();break;case'close-conditions':$('#conditions-dialog').close();trigger?.focus();break;}});
document.addEventListener('change',e=>{if(e.target.name==='gpu-candidate'){state.selected=e.target.value;renderGpu();dlg.querySelector(`input[value="${state.selected}"]`)?.focus();}if(e.target.id==='gpu-sort'){state.sort=e.target.value;renderGpu();$('#gpu-sort').focus();}if(e.target.id==='compatible'){state.compatible=e.target.checked;renderGpu();$('#compatible').focus();}});
document.addEventListener('input',e=>{if(e.target.id==='gpu-search'){state.query=e.target.value;const start=e.target.selectionStart;renderGpu();const input=$('#gpu-search');input.focus();try{input.setSelectionRange(start,start);}catch{ /* search inputs may not support selection */ }}});
document.addEventListener('submit',e=>{if(e.target.id==='chat-form'){e.preventDefault();const input=$('#request'),text=input.value;input.value='';request(text);}if(e.target.id==='conditions-form'){e.preventDefault();const d=new FormData(e.target),budgetValue=Number(d.get('budget'));if(!Number.isFinite(budgetValue)||budgetValue<70||budgetValue>300){notice('예산은 70~300만원으로 입력해주세요.');return;}state.budget=budgetValue*10000;state.resolution=d.get('resolution');$('#conditions-dialog').close();say(`예산 ${budgetValue}만원, 해상도 ${state.resolution} 조건을 반영했어요. 성능 데이터는 FHD 가상 예시입니다.`);render();}});
$('#request').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#chat-form').requestSubmit();}});
dlg.addEventListener('cancel',()=>trigger?.focus());$('#conditions-dialog').addEventListener('cancel',()=>trigger?.focus());
window.addEventListener('popstate',()=>{const screen=location.hash.slice(1);if(['welcome','results','detail','compare','final'].includes(screen)){state.screen=screen;render(false);}});
say('안녕하세요! 즐기는 게임과 예산을 알려주시면 나에게 맞는 PC를 함께 찾아드릴게요.');render(false);
})();
