(()=>{
'use strict';
const screen=document.querySelector('#builder-screen'), message=document.querySelector('#builder-message');
const labels={CPU:'CPU',GPU:'그래픽카드',RAM:'메모리',SSD:'SSD',MB:'메인보드',COOLER:'CPU쿨러',POWER:'파워',CASE:'케이스'};
let step=1,slot='CPU',source='sale',q='',offset=0,items=[],total=0,parts=[],title='',integrated=false,bundled=false,preview=null,busy=false,requestId=crypto.randomUUID(),saved=null,searchTimer;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const assemblyFee=window.PopcornAssemblyFee.ASSEMBLY_FEE;
const money=x=>Number(x||0).toLocaleString('ko-KR')+'원';
function note(text,error=false){message.textContent=text;message.className=error?'builder-error':'builder-success';}
async function api(url,body){const r=await fetch(url,{credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'입력 내용 또는 로그인 상태를 확인해 주세요.');return d;}
function input(){return {title,parts:parts.map(p=>({code:p.code,quantity:p.quantity,source:p.source})),integrated_gpu:integrated,bundled_cooler:bundled,request_id:requestId,preview_token:preview?.preview_token||null};}
function invalidate(){preview=null;saved=null;}
let loadVersion=0;
async function load(){const version=++loadVersion;try{const d=await api('/api/admin/pc-builder/parts?'+new URLSearchParams({slot,source,q,offset,limit:20}));if(version!==loadVersion)return;items=d.items;total=d.total;draw();}catch(e){note(e.message,true);}}
function draw(){document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.step)===step);b.disabled=busy;});
 if(saved){screen.innerHTML=`<section class="builder-card"><h2>검토 대기 제품군으로 등록했습니다</h2><p>${esc(saved.configuration_id)}</p><p>추천 승인과 고객 공개는 검토 후 별도로 진행합니다.</p><div class="builder-actions"><a href="/admin2/pc-workspace?id=${encodeURIComponent(saved.configuration_id)}">등록된 제품 검토하기</a><button id="builder-reset">다른 신규 구성 만들기</button></div></section>`;return;}
 if(step===2&&preview){const r=preview.review;screen.innerHTML=`<section class="builder-card"><h2>${esc(title)} · 구성·가격 확인</h2><p class="builder-note">DB 호환 검토 결과입니다. 미확인 사양과 실제 조립·부하 검수는 별도입니다. 검토 대기 저장은 호환성 통과·추천 승인이 아닙니다.</p><table class="builder-bom"><thead><tr><th>부품</th><th>제품 · 수량</th><th>금액</th></tr></thead><tbody>${preview.lines.map(p=>`<tr><td>${esc(labels[p.slot])}</td><td>${esc(p.name)} × ${p.quantity}<br><small>${p.source==='owned'?'DB 보유 부품':'판매 DB 부품'}</small></td><td>${money(p.total)}</td></tr>`).join('')}<tr><td colspan="2">조립비 · 한 번 포함</td><td>${money(preview.assembly_fee)}</td></tr></tbody></table><div class="builder-money"><span>예상 총액</span><b>${money(preview.total)}</b></div><h2>호환성 검사</h2>${r.checks.map(c=>`<div class="builder-check"><b class="builder-state-${esc(c.state)}">${{pass:'DB 규격 일치',fail:'불일치',unknown:'확인 필요'}[c.state]}</b>${esc(c.label)}<p class="builder-muted">${esc(c.detail)}</p></div>`).join('')}${r.blockers.length?`<h3>검토 시 보완할 항목</h3><ul>${r.blockers.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<p class="builder-note">${preview.duplicate_id?'같은 구성의 기존 제품군: '+esc(preview.duplicate_id):'동일한 부품·수량의 기존 제품군 없음'}<br>부품 자료·가격·재고·호환 규칙이 변경되면 다시 확인해야 합니다.</p><div class="builder-actions"><button data-step="1">부품 구성으로 돌아가기</button><button class="primary" id="builder-save" ${busy||!preview.can_save||preview.duplicate_id?'disabled':''}>${busy?'저장 중…':'검토 대기 제품군으로 저장'}</button></div></section>`;return;}
 screen.innerHTML=`<div class="builder-grid"><section class="builder-card"><h2>사용 가능한 부품 찾기</h2><div class="builder-controls"><select id="builder-source" aria-label="부품 출처"><option value="sale" ${source==='sale'?'selected':''}>판매 DB 부품</option><option value="owned" ${source==='owned'?'selected':''}>DB 재고가 있는 보유 부품</option></select><input class="builder-search" id="builder-search" aria-label="부품 검색" placeholder="제품명 또는 상품 코드" value="${esc(q)}"></div><div class="builder-slots">${Object.entries(labels).map(([k,v])=>`<button data-slot="${k}" class="${slot===k?'selected':''}">${v}</button>`).join('')}</div><p class="builder-muted">판매중이며 설명이 연결된 부품 ${total}개 · 재고는 DB 기준입니다. 실사·예약·출고 가능 여부는 별도입니다.</p>${items.map(p=>`<div class="builder-part"><img src="${esc(p.image_url)}" alt=""><div><strong>${esc(p.name)}</strong><small>${p.code} · DB 재고 ${p.stock_qty??'미확인'} · ${p.source_current?'원문 대조됨':'설명 갱신 필요'}</small><b>${money(p.unit_price)}</b></div><button data-add="${p.code}" ${!p.source_current||parts.some(x=>x.code===p.code)?'disabled':''}>추가</button></div>`).join('')||'<p>해당 조건의 부품이 없습니다.</p>'}<div class="builder-actions"><button id="builder-prev" ${offset===0?'disabled':''}>이전</button><span>${offset+1}–${Math.min(offset+20,total)} / ${total}</span><button id="builder-next" ${offset+20>=total?'disabled':''}>다음</button></div></section><section class="builder-card"><h2>현재 조립 구성</h2><label>상품명<input class="builder-title" id="builder-title" maxlength="180" placeholder="신규 PC 상품명" value="${esc(title)}"></label><table class="builder-bom"><tbody>${parts.map((p,i)=>`<tr><td>${esc(labels[p.slot])}</td><td>${esc(p.name)}<small class="builder-muted"><br>${p.source==='owned'?'DB 보유':'판매 DB'} · 개별 ${money(p.unit_price)}</small></td><td><input data-qty="${i}" type="number" min="1" max="${['RAM','SSD'].includes(p.slot)?16:1}" value="${p.quantity}" aria-label="${esc(labels[p.slot])} 수량"><button data-remove="${i}">제거</button></td></tr>`).join('')||'<tr><td>왼쪽에서 부품을 선택해 주세요.</td></tr>'}</tbody></table><label class="builder-option"><input id="builder-integrated" type="checkbox" ${integrated?'checked':''}> CPU 내장그래픽 사용 · 지원 근거 확인</label><label class="builder-option"><input id="builder-bundled" type="checkbox" ${bundled?'checked':''}> CPU 기본 쿨러 사용 · 포함 근거 확인</label><p class="builder-note">RAM 수량은 개별 모듈이 아닌 판매 패키지 수입니다. 예: 16GB × 2 세트는 수량 1개입니다.</p><div class="builder-money"><span>부품가 + 조립비 ${money(assemblyFee)}</span><b id="builder-estimate">${money(parts.reduce((s,p)=>s+p.unit_price*p.quantity,0)+assemblyFee)}</b></div><button class="primary" id="builder-preview" ${busy||!parts.length?'disabled':''}>${busy?'검사 중…':'구성·가격 확인 →'}</button></section></div>`;
 screen.querySelectorAll('input,select').forEach(el=>{el.disabled=busy;});
}
screen.addEventListener('input',e=>{const t=e.target;if(t.id==='builder-title'){title=t.value;invalidate();}if(t.dataset.qty!==undefined){parts[Number(t.dataset.qty)].quantity=Number(t.value);invalidate();const amount=document.querySelector('#builder-estimate');if(amount)amount.textContent=money(parts.reduce((s,p)=>s+p.unit_price*p.quantity,0)+assemblyFee);}if(t.id==='builder-search'){q=t.value;offset=0;clearTimeout(searchTimer);searchTimer=setTimeout(load,350);}});
screen.addEventListener('change',e=>{const t=e.target;if(t.id==='builder-source'){source=t.value;offset=0;load();}if(t.id==='builder-integrated'){integrated=t.checked;invalidate();}if(t.id==='builder-bundled'){bundled=t.checked;invalidate();}});
async function act(e){const t=e.target.closest('button');if(!t||busy)return;if(t.dataset.step){step=Number(t.dataset.step);if(step===2&&!preview){note('부품 구성에서 구성·가격 확인을 먼저 진행해 주세요.',true);step=1;}draw();return;}if(t.dataset.slot){slot=t.dataset.slot;offset=0;load();return;}if(t.dataset.add){const p=items.find(p=>p.code===Number(t.dataset.add));if(p){if(!['RAM','SSD'].includes(p.slot)&&parts.some(x=>x.slot===p.slot)){note('같은 종류의 부품을 제거한 뒤 추가해 주세요.',true);return;}parts.push({...p,quantity:1,source});invalidate();draw();}return;}if(t.dataset.remove!==undefined){parts.splice(Number(t.dataset.remove),1);invalidate();draw();return;}
 if(t.id==='builder-prev'||t.id==='builder-next'){offset+=t.id==='builder-next'?20:-20;load();return;}
 if(t.id==='builder-reset'){parts=[];title='';integrated=false;bundled=false;requestId=crypto.randomUUID();invalidate();step=1;note('새 구성을 시작합니다.');draw();return;}
 if(t.id==='builder-preview'||t.id==='builder-save'){busy=true;draw();try{const result=await api('/api/admin/pc-builder/'+(t.id==='builder-save'?'save':'preview'),input());if(t.id==='builder-save'){saved=result;note('검토 대기 저장 완료');}else{preview=result;step=2;note('현재 부품·가격·호환 규칙 기준으로 확인했습니다.');}}catch(e){if(t.id==='builder-save')preview=null;note(e.message,true);if(!preview)step=1;}finally{busy=false;draw();}}
}
screen.addEventListener('click',act);document.querySelector('.builder-steps').addEventListener('click',act);draw();load();
})();
