(function(){'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=x=>JSON.parse(JSON.stringify(x));
const labels={title:'상품명',intro:'상품 소개',benefits:'특장점',scene:'사용 상황',checks:'확인 안내',faq:'자주 묻는 질문'};
let data=null,step=1,group='',kind='part',query='',groupQuery='',focus='',selected=new Set(),work=new Map(),busy=false,cancel=false,instruction='고객이 이해하기 쉽게 설명을 다듬어 주세요. 구성 차이를 제품별로 반영하고 성능 수치를 만들지 마세요.',wanted=new Set(['intro']);
const message=s=>{$('batch-message').textContent=s;};
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});let v;try{v=await r.json();}catch{throw Error('응답을 읽지 못했습니다. 연결·로그인 상태를 확인해 주세요.');}if(!r.ok)throw Error(typeof v.detail==='string'?v.detail:'입력 형식과 권한을 확인해 주세요.');return v;}
function rows(){const g=data.groups.find(g=>g.key===group);return data.items.filter(p=>(!g||g.ids.includes(p.configuration_id))&&(!query||[p.title,p.configuration_id,p.facts.cpu,p.facts.gpu].join(' ').toLowerCase().includes(query.toLowerCase())));}
function picked(){return data.items.filter(p=>selected.has(p.configuration_id));}
function pending(){return picked().filter(p=>{const w=work.get(p.configuration_id);return w?.proposal&&w.fields.size&&!['saved','unchanged'].includes(w.result?.status);});}
function groups(){return data.groups.filter(g=>g.kind===kind&&(!groupQuery||[g.title,g.code].join(' ').toLowerCase().includes(groupQuery.toLowerCase())));}
function status(p){return p.management_state==='excluded'?'추천 제외 · 사유 확인':p.review_state==='approved'?'검토 승인':p.review_reasons?.length?'보완 항목 있음':'검토 대기';}
function display(v){if(typeof v==='string')return v;return JSON.stringify(v,null,2);}
function choices(w){return (w?.proposal?.changes||[]).filter(c=>w.fields.has(c.field));}
function draw(){if(!data)return;document.querySelectorAll('[data-step]').forEach(b=>{if(Number(b.dataset.step)===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');b.disabled=busy;});
if(step===1){$('batch-screen').innerHTML=`<div class="grid"><aside class="card"><h2>대상 묶음</h2><p class="muted">현재 ${data.catalog_total}개 제품군 · 묶음별 중복 포함</p><div class="toolbar"><select id="batch-kind" aria-label="묶음 기준"><option value="part" ${kind==='part'?'selected':''}>같은 부품</option><option value="reason" ${kind==='reason'?'selected':''}>같은 보완 사유</option></select></div><input id="batch-group-search" type="search" aria-label="묶음 검색" placeholder="부품명 · 코드 검색" value="${esc(groupQuery)}"><div class="group-list">${groups().map(g=>`<button class="group ${g.key===group?'active':''}" data-group="${esc(g.key)}"><strong>${esc(g.title)}</strong><small>${g.count}개 제품군${g.code?' · 부품 코드 '+esc(g.code):''}</small></button>`).join('')||'<p class="muted">해당 묶음이 없습니다.</p>'}</div><div class="advice">설명 보완과 사양 근거 보완은 별도 작업입니다. 알려진 불일치는 설명 수정으로 해소되지 않습니다.</div></aside><section class="card"><div class="toolbar"><h2>제품 선택</h2><input id="batch-find" type="search" aria-label="묶음 내 제품 검색" placeholder="제품명 · CPU · GPU 검색" value="${esc(query)}"><span>${selected.size} / ${data.max_batch}개 선택</span></div><div class="scroll"><table class="table"><thead><tr><th><input id="batch-all" type="checkbox" aria-label="현재 검색 결과 선택" ${rows().length&&rows().every(p=>selected.has(p.configuration_id))?'checked':''}></th><th>제품군 / 구성 차이</th><th>기준 가격</th><th>검토 상태</th></tr></thead><tbody>${rows().map(p=>`<tr><td><input type="checkbox" data-select="${esc(p.configuration_id)}" aria-label="${esc(p.configuration_id)} 선택" ${selected.has(p.configuration_id)?'checked':''}></td><td><b>${esc(p.title)}</b><small>${esc(p.configuration_id)} · ${esc(p.facts.cpu)} · ${esc(p.facts.gpu)}<br>RAM ${esc(p.facts.ram_gb)}GB · 저장 ${esc(p.facts.storage_gb)}GB</small></td><td>${p.price==null?'가격 확인 필요':Number(p.price).toLocaleString('ko-KR')+'원'}</td><td><span class="status">${esc(status(p))}</span></td></tr>`).join('')}</tbody></table></div><h3>보완 항목</h3><div class="field-picker">${Object.entries(labels).map(([k,l])=>`<label><input type="checkbox" data-wanted="${k}" ${wanted.has(k)?'checked':''}> ${l}</label>`).join('')}</div><textarea class="instructions" id="batch-instruction" maxlength="850" aria-label="AI 요청 내용">${esc(instruction)}</textarea><div class="advice">최대 ${data.max_batch}개씩 실제 AI를 호출합니다. 부품·가격·사양은 유지하며, 선택한 설명 항목만 제안합니다.</div><footer class="foot"><div><strong>상품 설명 초안 보완</strong><small>생성 결과는 브라우저에 보관됩니다. 저장 전 비교·선택이 필요합니다.</small></div><button class="primary" data-generate ${selected.size&&wanted.size?'':'disabled'}>선택 제품 AI 제안 생성 →</button></footer></section></div>`;
}else if(step===2){let p=picked().find(x=>x.configuration_id===focus)||picked()[0];if(!p){step=1;return draw();}focus=p.configuration_id;const w=work.get(focus),changes=w?.proposal?.changes||[];$('batch-screen').innerHTML=`<div class="changes"><aside class="card"><h2>선택 제품 ${selected.size}개</h2>${picked().map(p=>{const w=work.get(p.configuration_id);return `<button class="product-button ${p.configuration_id===focus?'active':''}" data-focus="${esc(p.configuration_id)}">${esc(p.title)}<small>${esc(p.configuration_id)} · ${w?.error?'생성 실패':w?.result?esc(w.result.message):w?.proposal?'제안 '+w.fields.size+'항목 선택':busy?'생성 대기':'미생성'}</small></button>`;}).join('')}<button data-generate>미생성·실패 제품 재시도</button><button data-regenerate>이 제품 제안 다시 생성</button></aside><section class="card"><h2>${esc(p.title)}</h2><p class="muted">${esc(p.configuration_id)} · ${esc(p.facts.cpu)} / ${esc(p.facts.gpu)} / RAM ${esc(p.facts.ram_gb)}GB / SSD ${esc(p.facts.storage_gb)}GB</p><div class="progress" role="status">${busy?'AI 제안 생성 중':'제품별 변경 항목을 선택합니다.'} ${busy?'<button id="batch-stop">현재 응답 후 중지</button>':''}</div>${w?.error?`<p class="error">${esc(w.error)}</p>`:''}${changes.map(c=>`<div class="proposal-field"><label class="field-choice"><input data-patch="${c.field}" type="checkbox" ${w.fields.has(c.field)?'checked':''}>${labels[c.field]} 변경 적용</label><div class="compare"><article><h3>현재 저장된 설명</h3>${esc(display(w.detail.content[c.field]))}</article><article><h3>AI 제안</h3>${esc(display(c.value))}</article></div><div class="reason"><b>변경 이유</b><br>${esc(c.reason)}</div></div>`).join('')||(!busy&&!w?.error?'<p>선택한 항목에 대한 변경 제안이 없습니다.</p>':'')}<ul class="muted">${(w?.proposal?.notes||[]).map(n=>`<li>${esc(n)}</li>`).join('')}</ul>${w?.proposal?.model?`<p class="muted">${esc(w.proposal.provider)} · ${esc(w.proposal.model)} · 현재 등록 근거</p>`:''}<div class="advice">AI 의견은 검토 참고 자료입니다. 설명 선택 적용은 호환성·추천 승인이 아닙니다.</div><footer class="foot"><button data-prev>← 대상 선택</button><button class="primary" data-next ${pending().length?'':'disabled'}>저장 내용 확인 →</button></footer></section></div>`;
}else{$('batch-screen').innerHTML=`<section class="card"><h2>적용 범위 확인</h2><p class="muted">최신 버전과 근거를 다시 대조한 후 선택한 설명만 저장합니다.</p><div class="summary"><article class="card">선택 제품<strong>${selected.size}</strong></article><article class="card">저장 대상<strong>${pending().length}</strong></article><article class="card">구성·가격 변경<strong>없음</strong></article></div><div class="scroll"><table class="table"><thead><tr><th>제품군</th><th>적용 항목</th><th>저장 상태</th></tr></thead><tbody>${picked().map(p=>{const w=work.get(p.configuration_id);return `<tr><td><b>${esc(p.title)}</b><small>${esc(p.configuration_id)} · 기준 버전 ${w?.detail?.revision??p.revision}</small></td><td>${choices(w).map(c=>labels[c.field]).join(', ')||'적용 제외'}</td><td>${w?.result?`<span class="${['saved','unchanged'].includes(w.result.status)?'good':'error'}">${esc(w.result.message)}</span>`:w?.error?`<span class="error">${esc(w.error)}</span>`:choices(w).length?'저장 대기 → 검토 필요':'기존 내용 유지'}${['conflict','failed'].includes(w?.result?.status)?`<br><button data-refresh="${esc(p.configuration_id)}">최신 정보로 다시 제안</button>`:''}<br><a href="/admin2/pc-workspace?id=${encodeURIComponent(p.configuration_id)}">개별 검토 →</a></td></tr>`;}).join('')}</tbody></table></div><div class="advice">변경된 제품은 덮어쓰지 않고 충돌·실패를 개별로 표시합니다. 이미 성공한 제품은 다시 저장하지 않습니다. 변경 이력을 남기며 추천·공개 승인은 별도입니다.</div><footer class="foot"><button data-prev>← 제안 비교</button><button class="primary" data-save ${pending().length?'':'disabled'}>선택한 설명 ${pending().length}개 제품 저장</button></footer></section>`;}
if(busy)document.querySelectorAll('.batch button,.batch input,.batch select,.batch textarea').forEach(b=>b.disabled=b.id!=='batch-stop');
}
async function generate(only){if(busy)return;const targets=picked().filter(p=>(!only||p.configuration_id===only)&&!work.get(p.configuration_id)?.proposal);if(!targets.length){message('생성할 제품이 없습니다. 기존 제안을 비교해 주세요.');step=2;draw();return;}busy=true;cancel=false;step=2;draw();let done=0;
try{for(const p of targets){if(cancel)break;const id=p.configuration_id;message(`AI 제안 ${++done} / ${targets.length} · ${p.title}`);try{const detail=await api('/api/admin/pc-configurations/'+encodeURIComponent(id));const proposal=await api('/api/admin/pc-configurations/'+encodeURIComponent(id)+'/ai-proposals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:detail.revision,mode:'copy',instruction:instruction+'\n변경 항목은 '+[...wanted].join(', ')+'만 제안하세요.'})});proposal.changes=proposal.changes.filter(c=>wanted.has(c.field));work.set(id,{detail,proposal,fields:new Set(proposal.changes.map(c=>c.field))});}catch(e){work.set(id,{error:e.message,fields:new Set()});}draw();}}finally{busy=false;message(cancel?'생성을 중지했습니다. 완료된 제안은 유지됩니다.':'생성 결과를 확인해 주세요. 실패 제품은 개별 재시도할 수 있습니다.');draw();}}
async function save(){if(busy)return;const targets=pending();if(!targets.length)return;const items=targets.map(p=>{const w=work.get(p.configuration_id);return {configuration_id:p.configuration_id,revision:w.proposal.revision,source_basis:w.proposal.source_basis,changes:choices(w)};});busy=true;draw();message('선택한 설명 저장 중…');try{const result=await api('/api/admin/pc-workspace/batch-description',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});result.items.forEach(r=>{work.get(r.configuration_id).result=r;});message(`저장 ${result.counts.saved} · 동일 내용 ${result.counts.unchanged} · 충돌 ${result.counts.conflict} · 실패 ${result.counts.failed}`);}catch(e){message(e.message+' 생성된 제안과 선택은 유지됩니다.');}finally{busy=false;draw();}}
document.querySelector('.batch').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='batch-stop'){cancel=true;message('진행 중인 응답까지 받은 뒤 중지합니다.');return;}if(busy)return;if(b.dataset.group){group=b.dataset.group;query='';draw();}if(b.dataset.focus){focus=b.dataset.focus;draw();}if(b.dataset.step){const target=Number(b.dataset.step);if(target>1&&!selected.size)return;step=target;draw();}if(b.hasAttribute('data-generate'))generate();if(b.hasAttribute('data-next')){step++;draw();}if(b.hasAttribute('data-prev')){step--;draw();}if(b.hasAttribute('data-save'))save();if(b.hasAttribute('data-regenerate')&&!['saved','unchanged'].includes(work.get(focus)?.result?.status)){work.delete(focus);generate(focus);}if(b.dataset.refresh){work.delete(b.dataset.refresh);generate(b.dataset.refresh);}});
document.querySelector('.batch').addEventListener('input',e=>{if(busy)return;if(e.target.id==='batch-instruction'){instruction=e.target.value;return;}const id=e.target.id;if(id==='batch-find'||id==='batch-group-search'){if(id==='batch-find')query=e.target.value;else groupQuery=e.target.value;draw();$(id).focus();}});
document.querySelector('.batch').addEventListener('change',e=>{if(busy)return;const x=e.target;if(x.id==='batch-kind'){kind=x.value;group=groups()[0]?.key||'';draw();}if(x.dataset.select){if(x.checked&&selected.size>=data.max_batch){x.checked=false;message(`한 번에 ${data.max_batch}개까지 선택할 수 있습니다.`);return;}x.checked?selected.add(x.dataset.select):selected.delete(x.dataset.select);draw();}if(x.id==='batch-all'){const visible=rows();if(x.checked){const union=new Set([...selected,...visible.map(p=>p.configuration_id)]);if(union.size>data.max_batch){x.checked=false;message(`최대 ${data.max_batch}개씩 선택해 주세요. 검색으로 범위를 줄일 수 있습니다.`);return;}selected=union;}else visible.forEach(p=>selected.delete(p.configuration_id));draw();}if(x.dataset.patch){const w=work.get(focus);if(['saved','unchanged'].includes(w?.result?.status)){message('저장 완료 제품은 개별 작업에서 다시 수정해 주세요.');draw();return;}x.checked?w.fields.add(x.dataset.patch):w.fields.delete(x.dataset.patch);draw();}if(x.dataset.wanted){x.checked?wanted.add(x.dataset.wanted):wanted.delete(x.dataset.wanted);draw();}});
window.addEventListener('beforeunload',e=>{if(busy||pending().length){e.preventDefault();e.returnValue='';}});
api('/api/admin/pc-workspace/groups').then(v=>{data=v;group=data.groups.find(g=>g.code==='113800')?.key||data.groups[0]?.key||'';draw();}).catch(e=>message(e.message));
})();
