(()=>{'use strict';
const root=document.querySelector('#media-root'),msg=document.querySelector('#media-message'),id=new URLSearchParams(location.search).get('id');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,busy=false,timer;
const base='/api/admin/pc-media/'+encodeURIComponent(id||'');
async function api(url,body){const r=await fetch(url,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'입력·로그인 상태 확인 필요');return d;}
function render(){const s=state,casePart=s.snapshot.parts.find(p=>p.slot==='CASE');
root.innerHTML=`<div class="pcm-grid"><section class="builder-card"><h2>${esc(s.title)}</h2>${casePart?`<img class="pcm-reference" src="/api/product-images/${casePart.code}/detail" alt="케이스 기준 사진"><h3>케이스 기준 사진</h3><p>${esc(casePart.name)}</p>`:''}<h3>이미지 반영 구성</h3><ul>${s.snapshot.parts.map(p=>`<li>${esc(p.slot)} · ${esc(p.name)} × ${p.quantity}</li>`).join('')}</ul><p>냉각 방식 · ${esc(s.snapshot.cooling.method_label||s.snapshot.cooling.installed)}</p><p class="builder-note">케이스 외형·투명 패널·냉각 방식·관찰 가능한 LED를 기준으로 생성합니다. 실제 출고 사진은 아닙니다.</p></section><section class="builder-card"><h2>생성 전 확인</h2>${s.errors.length?`<ul class="builder-error">${s.errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="builder-success">전체 구성 및 현재 DB 호환 규격 확인 완료</p>'}${s.assembly_checks.length?`<details><summary>실제 조립 시 확인 ${s.assembly_checks.length}항목</summary><ul>${s.assembly_checks.map(x=>`<li>${esc(x.label)} · ${esc(x.detail)}</li>`).join('')}</ul></details>`:''}<p class="pcm-model">생성 모델 · ${esc(s.model)}</p><p class="builder-note">버튼 실행 시 이미지 API 비용 발생 · 1회 1장 · 자동 일괄 생성·자동 대표 선택 없음. 생성 실패는 자동 재호출하지 않습니다.</p>${!s.cloud_ready?'<p class="builder-error">클라우드 저장·조회 연결 확인 필요</p>':''}${!s.provider_ready?'<p class="builder-error">이미지 API 설정 필요</p>':''}<button id="pcm-generate" class="primary" ${busy||s.errors.length||!s.provider_ready||!s.cloud_ready||s.jobs.some(j=>j.status==='running'&&!j.interrupted)?'disabled':''}>${busy?'요청 중…':'대표 이미지 1장 생성'}</button><button id="pcm-refresh" ${busy?'disabled':''}>최신 구성·검사 다시 확인</button><h2>생성 이미지</h2><div class="pcm-jobs">${s.jobs.map(j=>`<article class="pcm-job ${j.selected?'selected':''}"><strong>${j.selected?'현재 대표 이미지':j.status==='ready'?'선택 전 미리보기':j.status==='running'?'생성·저장 진행 중':'처리 실패'}</strong><p>${esc(j.created_at)}</p>${j.status==='ready'?`<img src="${esc(j.image_url)}" alt="AI 조립 예시 이미지"><p>${esc(s.snapshot.notice)}</p><p>${j.current?'현재 구성 기준':'구성·자료 변경 · 대표 선택 불가'}</p><button data-select="${esc(j.job_id)}" ${busy||!j.current||j.selected?'disabled':''}>대표 이미지로 선택</button>`:`<p class="pcm-status">${esc(j.error||j.phase)}</p>${j.interrupted?'<p>작업 중단 가능 · 자동 재생성 없음. 처리 상태 확인 후 신규 생성 가능</p>':''}${j.status==='failed'&&j.phase==='storage'?`<button data-retry="${esc(j.job_id)}" ${busy?'disabled':''}>클라우드 저장만 재시도 · 생성 비용 없음</button>`:''}`}</article>`).join('')||'<p>등록된 생성 이미지 없음</p>'}</div></section></div>`;
}
async function load(){clearTimeout(timer);try{state=await api(base);render();if(state.jobs.some(j=>j.status==='running'&&!j.interrupted))timer=setTimeout(load,5000);}catch(e){msg.textContent=e.message;}}
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.id==='pcm-refresh'){await load();return;}busy=true;render();try{if(b.id==='pcm-generate'){const request_id=crypto.randomUUID();await api(base+'/generate',{request_id,basis:state.basis});msg.textContent='생성 요청 등록 완료 · 현재 화면에서 진행 상태 확인';}if(b.dataset.select){await api(base+'/select',{job_id:b.dataset.select,visual_basis:state.visual_basis});msg.textContent='대표 이미지 선택 완료 · 제품군 목록 반영';}if(b.dataset.retry){await api(base+'/retry-storage/'+b.dataset.retry,{});msg.textContent='클라우드 저장 재시도 등록';}}catch(e){msg.textContent=e.message;}finally{busy=false;await load();}});
if(!id){root.textContent='제품군 목록·작업 공간에서 제품 선택 후 대표 이미지 관리 실행';return;}document.querySelector('#media-back').href='/admin2/pc-workspace?id='+encodeURIComponent(id);document.querySelector('#media-back').textContent='제품 작업 공간';load();
})();