(()=>{'use strict';
const root=document.querySelector('#media-root'),msg=document.querySelector('#media-message'),id=new URLSearchParams(location.search).get('id');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,busy=false,timer,filter="all";
const base='/api/admin/pc-media/'+encodeURIComponent(id||'');
async function api(url,body){const r=await fetch(url,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'입력·로그인 상태 확인 필요');return d;}
const labels={CPU:'CPU',GPU:'그래픽카드',RAM:'메모리',SSD:'SSD',HDD:'HDD',MB:'메인보드',POWER:'파워',CASE:'케이스',COOLER:'CPU 쿨러',COOLER_CPU_AIR:'공랭 쿨러',COOLER_CPU_AIO:'수랭 쿨러'};
const dateLabel=v=>String(v||'').slice(0,16).replace('T',' ');
const origin=j=>j.origin_kind==='generated'?'generated':j.origin_kind==='existing_import'?'import':'unknown';
const originLabel=j=>({generated:'AI 생성',import:'기존 원본 반입',unknown:'출처 미확인'})[origin(j)];
function statusLabel(j){const o=origin(j);if(j.status==='ready')return {generated:'생성·저장 완료',import:'등록 완료',unknown:'준비됨'}[o];if(j.status==='running'){if(o==='generated')return {generation:'이미지 생성 중',storage:'생성 이미지 저장 중'}[j.phase]||'생성 처리 중 · 단계 확인 필요';if(o==='import')return j.phase==='import_storage'?'원본 등록·저장 중':'원본 등록 처리 중 · 단계 확인 필요';return '처리 중';}if(j.status==='failed'){if(o==='generated')return {generation:'이미지 생성 실패',storage:'생성 이미지 저장 실패'}[j.phase]||'생성 처리 실패 · 단계 확인 필요';if(o==='import')return j.phase==='import_failed'?'원본 등록 실패':'원본 등록 처리 실패 · 단계 확인 필요';return '처리 실패';}return '상태 확인 필요';}
function busyLabel(jobs){const active=jobs.filter(j=>j.status==='running'&&!j.interrupted);if(active.every(j=>origin(j)==='generated'))return '생성·저장 진행 중';if(active.every(j=>origin(j)==='import'))return '원본 등록·저장 진행 중';return '이미지 작업 진행 중';}
function card(j,s){const o=origin(j),retry=o==='generated'&&j.status==='failed'&&j.phase==='storage';const model=o==='import'?'해당 없음':j.model||'모델 기록 없음';return `<article class="pca-job ${j.selected?'selected':''}"><header class="pca-job-head"><span class="pca-chip origin-${o}">${originLabel(j)}</span><span class="pca-chip ${j.status==='failed'?'status-failed':j.status==='ready'?'good':'warn'}">${statusLabel(j)}</span></header>${j.status==='ready'?`<img src="${esc(j.image_url)}" alt="${originLabel(j)} 이미지"><p>${esc(o==='generated'?s.snapshot.notice:'이미지 예시 · 실제 출고 사진이 아닙니다. 원본 생성 이력은 확인되지 않았습니다.')}</p>`:`<p class="job-note">${statusLabel(j)}</p>${j.interrupted?'<p>작업 중단 가능 · 상태 확인 필요</p>':''}${retry?(j.staged_available?`<img src="${esc(j.image_url)}" alt="클라우드 저장 전 생성 원본"><p>클라우드 저장 전 원본</p>`:'<p>생성 원본 조회 불가 · 별도 재생성 필요</p>'):''}`}<dl class="origin-meta"><dt>원본 생성</dt><dd>${o==='unknown'?'시각·생성자 미확인':'시각·생성자 기록 없음'}</dd><dt>${o==='import'?'이번 등록 모델':o==='generated'?'생성 모델':'모델 기록'}</dt><dd>${esc(model)}${o==='import'?'<span class="sub">기존 원본 반입 · 생성 실행 없음</span>':''}</dd><dt>현재 등록</dt><dd><time>${esc(dateLabel(j.created_at))||'기록 없음'}</time><span class="sub">요청이 기록된 시각</span></dd><dt>등록 주체</dt><dd>미확인</dd></dl><hr class="origin-separation"><dl class="origin-meta"><dt>원본 재사용</dt><dd>미확인</dd><dt>대표 선택</dt><dd>${j.selected?'선택됨':'미선택'}</dd><dt>고객 공개</dt><dd>미확인<span class="sub">등록·선택 상태로 추정하지 않음</span></dd></dl><details><summary>출처·재사용 정보</summary><p>출처: ${originLabel(j)}</p><p>원본 생성 정보는 현재 등록 시각·주체로 대체하지 않습니다. 재사용 승인과 현재 등록 권한·고객 공개는 별도입니다.</p></details>${j.status==='ready'?`<button data-select="${esc(j.job_id)}" ${busy||!j.current||j.selected?'disabled':''}>${j.selected?'대표 이미지 사용 중':j.current?'대표 이미지로 선택':'현재 구성과 다름'}</button>`:retry?`<button data-retry="${esc(j.job_id)}" ${busy||!s.cloud_ready||!j.staged_available?'disabled':''}>클라우드 저장만 재시도</button>`:''}</article>`;}
function render(){const s=state,casePart=s.snapshot.parts.find(p=>p.slot==='CASE'),selected=s.jobs.find(j=>j.selected&&j.status==='ready'),running=s.jobs.some(j=>j.status==='running'&&!j.interrupted),ready=!s.errors.length;
const preview=selected?selected.image_url:casePart?'/api/product-images/'+encodeURIComponent(casePart.code)+'/detail':null;
const shown=s.jobs.filter(j=>filter==='all'||j.current);
const check=(ok,title,note)=>`<div class="pca-check ${ok?'good':'warn'}"><b>${ok?'✓':'!'}　${title}</b><span>${esc(note)}</span></div>`;
root.innerHTML=`<section class="pca-product"><span class="pca-code">${esc(id)}</span><strong>${esc(s.title)}</strong><div class="pca-tags"><span class="pca-chip ${ready?'good':'warn'}">${ready?'구성·규격 확인':'구성 확인 필요'}</span><span class="pca-chip">${selected?'대표 이미지 선택됨':'대표 이미지 미선택'}</span></div></section><div class="pca-grid"><section class="pca-card"><h2>${selected?'현재 대표 이미지':'케이스 기준 사진'}</h2>${preview?`<div class="pca-stage"><img src="${esc(preview)}" alt="${selected?'현재 선택된 대표 이미지':'등록된 케이스 기준 사진'}"><span class="pca-chip">${selected?originLabel(selected):'생성 기준 사진'}</span></div>`:'<div class="pca-empty">등록된 기준 사진 없음</div>'}<p>${esc(casePart?.name||'케이스 정보 확인 필요')}</p>${selected&&!selected.current?'<p class="pca-notice">구성·자료 변경 · 현재 구성 기준의 새 이미지 확인 필요</p>':''}<details><summary>이미지에 반영할 부품 구성 보기</summary><ul class="pca-bom">${s.snapshot.parts.map(p=>`<li><b>${esc(labels[p.slot]||p.slot)}</b> · ${esc(p.name)} × ${esc(p.quantity)}</li>`).join('')}</ul></details></section><section class="pca-card"><h2>생성 준비</h2><div class="pca-checks">${check(ready,'부품 구성·현재 호환 규격',ready?'DB 규격 확인 완료':'아래 확인 사항 참조')}${check(s.provider_ready,'이미지 생성 연결',s.provider_ready?'사용 가능':'API 설정 필요')}${check(s.cloud_ready,'클라우드 저장 연결',s.cloud_ready?'사용 가능':'연결 확인 필요')}</div>${s.errors.length?`<ul class="pca-errors">${s.errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<h3>생성 기준</h3><table class="pca-facts"><tbody><tr><th>케이스</th><td>등록된 케이스 외형·투명 패널</td></tr><tr><th>냉각</th><td>${esc(s.snapshot.cooling.method_label||s.snapshot.cooling.installed||'확인 필요')}</td></tr><tr><th>조명</th><td>관찰 가능한 LED 기준</td></tr></tbody></table><p class="pca-notice">실제 출고 사진이 아닌 조립 예시 이미지입니다.</p>${s.assembly_checks.length?`<details><summary>실제 조립 시 확인 ${s.assembly_checks.length}항목</summary><ul class="pca-bom">${s.assembly_checks.map(x=>`<li>${esc(x.label)} · ${esc(x.detail)}</li>`).join('')}</ul></details>`:''}<div class="pca-actions"><button id="pcm-generate" class="primary" ${busy||!ready||!s.provider_ready||!s.cloud_ready||running?'disabled':''}>${busy?'요청 중…':running?busyLabel(s.jobs):'대표 이미지 1장 생성'}</button><button id="pcm-refresh" ${busy?'disabled':''}>구성·검사 다시 확인</button></div><p class="pca-cost">실행 시 이미지 API 비용 발생 · 자동 생성·자동 대표 선택 없음</p><details><summary>생성 모델·실패 처리 안내</summary><p>${esc(s.model)}</p><p>생성 실패 시 자동 재호출 없음. 저장 실패 시 원본이 남아 있으면 저장만 재시도 가능.</p></details></section></div><section class="pca-card"><header class="pca-gallery-head"><h2>이미지 목록</h2><div class="pca-filters" aria-label="이미지 필터"><button data-filter="all" aria-pressed="${filter==='all'}">전체</button><button data-filter="current" aria-pressed="${filter==='current'}">현재 구성</button></div><small>${shown.length}건</small></header><div class="pca-jobs">${shown.map(j=>card(j,s)).join('')||'<div class="pca-empty">'+(filter==='current'?'현재 구성의 이미지 없음':'등록된 이미지 없음')+'</div>'}</div></section>`;
}
async function load(){clearTimeout(timer);try{state=await api(base);render();if(state.jobs.some(j=>j.status==='running'&&!j.interrupted))timer=setTimeout(load,5000);}catch(e){msg.textContent=e.message;}}
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.filter){filter=b.dataset.filter;render();return;}if(b.id==='pcm-refresh'){await load();return;}busy=true;render();try{if(b.id==='pcm-generate'){const request_id=crypto.randomUUID();await api(base+'/generate',{request_id,basis:state.basis});msg.textContent='생성 요청 등록 완료 · 현재 화면에서 진행 상태 확인';}if(b.dataset.select){await api(base+'/select',{job_id:b.dataset.select,visual_basis:state.visual_basis});msg.textContent='대표 이미지 선택 완료 · 제품군 목록 반영';}if(b.dataset.retry){await api(base+'/retry-storage/'+b.dataset.retry,{});msg.textContent='클라우드 저장 재시도 등록';}}catch(e){msg.textContent=e.message;}finally{busy=false;await load();}});
if(!id){root.textContent='제품군 목록·작업 공간에서 제품 선택 후 대표 이미지 관리 실행';return;}document.querySelector('#media-back').href='/admin2/pc-workspace?id='+encodeURIComponent(id);document.querySelector('#media-back').textContent='제품 작업 공간';document.querySelector('#media-video').href='/admin2/pc-video?id='+encodeURIComponent(id);load();
})();