(()=>{'use strict';
const root=document.querySelector('#video-root'),msg=document.querySelector('#video-message'),id=new URLSearchParams(location.search).get('id');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base='/api/admin/pc-video/'+encodeURIComponent(id||'');let state,music='hyper-ultra',busy=false,timer;
async function api(url,body){const r=await fetch(url,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'입력·로그인 상태 확인 필요');return d;}
function render(){const s=state.choices[music],p=s.snapshot;
root.innerHTML=`<div class="pcm-grid"><section class="builder-card"><h2>${esc(p.title)}</h2>${p.image_job_id?`<img class="pcm-reference" src="/api/admin/pc-media/${encodeURIComponent(id)}/images/${esc(p.image_job_id)}" alt="영상 원본 대표 이미지">`:''}<p>CPU · ${esc(p.facts.cpu||'확인 필요')}</p><p>GPU · ${esc(p.facts.gpu||'내장 그래픽')}</p><p>메모리 ${esc(p.facts.ram_gb)}GB · 저장 ${esc(p.facts.storage_gb)}GB</p><p>${esc(p.cooling)}</p><a href="/admin2/pc-media?id=${encodeURIComponent(id)}">대표 이미지 확인·관리 →</a></section><section class="builder-card"><h2>영상 제작 설정</h2><p>10초 · 1920×1080 · 30fps · MP4</p><p class="builder-note">5장면의 빠른 확대·전환과 큰 글자, 흰색 5px 글자 외곽선. 실제 3D 회전 영상이 아닌 대표 사진 편집입니다. 추가 이미지·영상 AI API 비용 없음. 서버 렌더링·저장 자원 사용.</p><label for="pcv-music">배경 음악</label><select id="pcv-music" ${busy?'disabled':''}><option value="none" ${music==='none'?'selected':''}>음악 없음</option>${state.tracks.map(t=>`<option value="${esc(t.id)}" ${music===t.id?'selected':''}>${esc(t.title)} · CC0</option>`).join('')}</select>${music!=='none'?`<audio controls preload="none" src="/api/admin/pc-video-music/${esc(music)}"></audio><p>${esc(state.tracks.find(t=>t.id===music)?.author)} · <a target="_blank" rel="noopener" href="${esc(state.tracks.find(t=>t.id===music)?.source)}">음원 출처·라이선스</a></p>`:''}<p class="builder-note">사용자 제작 엔딩 파일 대기 · 이번 영상은 본편만 제작</p>${s.errors.length?`<ul class="builder-error">${s.errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`:'<p class="builder-success">현재 구성·호환 규격·대표 이미지 확인 완료</p>'}${!state.renderer_ready?'<p class="builder-error">렌더러·한글 글꼴·음원 설정 확인 필요</p>':''}${!state.cloud_ready?'<p class="builder-error">클라우드 저장 연결 확인 필요</p>':''}<button id="pcv-generate" class="primary" ${busy||s.errors.length||!state.renderer_ready||!state.cloud_ready||state.jobs.some(j=>j.status==='running'&&!j.interrupted)?'disabled':''}>${busy?'요청 중…':'소개 영상 생성'}</button><button id="pcv-refresh">최신 상태 조회</button><h2>생성 영상</h2><div class="pcm-jobs">${state.jobs.map(j=>`<article class="pcm-job"><strong>${j.status==='ready'?'완료':j.status==='running'?'제작·저장 중':'처리 실패'} · ${esc(j.music)}</strong><p>${esc(j.created_at)}</p>${j.status==='ready'?`<video controls preload="metadata" playsinline poster="${esc(j.thumb_url)}" src="${esc(j.url)}"></video><p>${j.current?'현재 구성 기준':'구성·설명·대표 이미지 변경 · 이전 버전'}</p><a href="${esc(j.url)}?download=true">MP4 다운로드</a>`:`<p>${esc(j.error||j.phase)}</p>${j.interrupted?'<p>작업 중단 가능 · 자동 재제작 없음</p>':''}${j.status==='failed'&&j.phase==='storage'?`<button data-retry="${esc(j.job_id)}" ${busy||!j.staged_available||!state.cloud_ready?'disabled':''}>클라우드 저장만 재시도</button>`:''}`}</article>`).join('')||'<p>등록된 영상 없음</p>'}</div></section></div>`;}
async function load(){clearTimeout(timer);try{state=await api(base);render();if(state.jobs.some(j=>j.status==='running'&&!j.interrupted))timer=setTimeout(load,5000);}catch(e){msg.textContent=e.message;}}
root.addEventListener('change',e=>{if(e.target.id==='pcv-music'){music=e.target.value;render();}});
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.id==='pcv-refresh'){await load();return;}busy=true;render();try{if(b.id==='pcv-generate'){const d=await api(base+'/generate',{request_id:crypto.randomUUID(),basis:state.choices[music].basis,music});msg.textContent=d.reused?'동일 원본·설정의 완료 영상 재사용':'영상 제작 요청 등록 · 완료 후 클라우드 저장';}if(b.dataset.retry){await api(base+'/retry-storage/'+b.dataset.retry,{});msg.textContent='클라우드 저장만 재시도 등록';}}catch(e){msg.textContent=e.message;}finally{busy=false;await load();}});
if(!id){root.textContent='제품을 선택한 뒤 영상 관리 실행';return;}document.querySelector('#video-back').href='/admin2/pc-media?id='+encodeURIComponent(id);document.querySelector('#video-back').textContent='대표 이미지 관리';load();
})();
